### ISSUE TITLE
Umbau der Kopier- und Verschiebefunktion

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/News-with-Images#11]
* wie von Bianka vorgeschlagen mit Checkbosen in der Übersicht, Radio-Buttons "kopieren" und "verschieben" plus "Weiter"-Button und auf nächster Seite Auswahl des Ziels, so wie momentan bei der Gruppenauswahl
* zusätzlich innerhalb der Post-Bearbeitungsansicht auch nochmal Radio-Buttons "kopieren" und "verschieben" plus "Weiter"-Button

**Comment by mrbaseman** [comment]
ist mit https://github.com/WBCE/News-with-Images/commit/cba593e6db13a0dcff329f2bc98dd92cd19fdab9 implementiert.

Das gewohnte Verhalten beim Erstellen eines Posts habe ich damit wiederhergestellt.
Die Möglichkeit beim Bearbeiten eines Posts über die Auswahl der Gruppe zu verschieben habe ich beibehalten, weil es einfach praktisch ist von dort aus das neue Ziel auszuwählen bevor man auf Speichern klickt. Aus dem Beitrag heraus diesen auch kopieren zu können braucht man vielleicht nicht unbedingt, oder? 
Wenn das gewünscht ist, dann ist es jetzt auch kein großer Aufwand mehr eine Kopier- und Verschiebefunktion analog zur Übersichtsseite in die Beitragsbearbeitung mit zu integrieren.

**Comment by instantflorian** [comment]
Ist leider noch ein kleiner Fehler drin. Beim Kopieren wird eine Notice "variable link not defined" angezeigt. Auf der Übersichtsseite im FE ist dann dadurch kein Link zum kopierten Beitrag hinterlegt. Dieser wird erst erzeugt, wenn man den Beitrag zum Bearbeiten öffnet und die Überschrift ändert (und die Änderungen speichert)
Es wäre glaube ich auch sinnvoll, kopierte Beiträge per Default auf active:0 zu setzen, damit diese nicht sofort im FE erscheinen, was u.U. nicht gewünscht ist.

**Comment by instantflorian** [comment]
In der Zielauswahl erscheint außerdem eine Notice, sobald es Gruppen auf der Seite gibt:
![2019-04-28_061115](https://user-images.githubusercontent.com/1433754/56858596-d14f3100-697c-11e9-8bbd-2ae94ce448e0.jpg)

**Comment by mrbaseman** [comment]
Link hinterlegen und Kopie des Posts deaktivieren ist jetzt mit https://github.com/WBCE/News-with-Images/commit/7dd371d56484a342e88d42a566b59dee101ed9e8 implementiert

**Comment by mrbaseman** [comment]
...und die Notice ist mit https://github.com/WBCE/News-with-Images/commit/dd711617a09c16a15cb6d68647fcc094f90f7d14 repariert. Da hatte ich eine vorselektierte Gruppe, die es bei der alten Kopiermethode gegeben hat mit kopiert, aber wenn man mehrere Beiträge selektieren kann, die womöglich zu unterschiedlichen Gruppen gehören, dann macht das sowieso keinen Sinn.
