### ISSUE TITLE
import von Topics und klassischem News

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/News-with-Images#13]
Wunsch aus dem Forum:
https://forum.wbce.org/viewtopic.php?pid=23607#p23607

**Comment by webbird** [comment]
* Die Tabellen sehen doch recht ähnlich aus, so dass ein Import nicht ganz unrealistisch erscheint
* Topics erlaubt Installation unter verschiedenen Namen. Hier haben wir die Möglichkeit nur den Namen Topics zum Import anzubieten oder man sucht in allen Modultabellen, was eventuell zu Topics gehören könnte. Wenn Tabellen ein Feld namens topic_id haben, sind sie wahrscheinlich geeignete Kandidaten
* Gruppen gibt es in Topics nicht, sprich: Topics Beiträge werden einfach ohne Gruppe übernommen
* Topics Master gibt es in News nicht; Master-Sections kann man daher nicht importieren 
* Description und Keywords gibt es in News nicht, ebensowenig die Möglichkeit Webseite und email in separaten Feldern zu hinterlegen

**Comment by mrbaseman** [comment]
as a first step I have implemented the feature to import complete "News with Images"-sections (including the posts) in [3.7.13](https://github.com/WBCE/News-with-Images/commit/22e3f3e96f0c779bc80a17059753d25cfb76f816). 
Create a new section (which does not yet contain posts or groups). Then you are offered a list of possible sections from where you can import. 
I plan to extend that list of sections by the classical news sections and topics sections. Depending on the source module type the steps during import will be slightly different (e.g. the classical news has no galleries to import, topics stores data in a different manner in the database)

**Comment by mrbaseman** [comment]
so, klassische News-Sections kann man mit https://github.com/WBCE/News-with-Images/commit/5ca5daa9d384a81224d985d1758b7d3f08953a5a auch importieren, wobei man zuerst im klassischen News-Modul ein paar require in require_once ändern musste, damit es unter WBCE master überhaupt läuft. 
Ich bezieh mich auf die Version, die mit WB 2.8.3 ausgeliefert worden ist. Vermutlich geht es mehr oder weniger auch mit neueren News Versionen aus 2.10 oder 2.12... 
Kommentare werden nicht mit importiert, da NWI die ja auch nicht kennt.

**Comment by instantflorian** [comment]
Sehr gut umgesetzt.

**Comment by mrbaseman** [comment]
danke, Topics geht jetzt auch mit https://github.com/WBCE/News-with-Images/commit/12b5b92f0e706d30c971e0b381d471c5fa5861e3

**Comment by mrbaseman** [comment]
Settings aus Topics werden irgendwie noch nicht richtig übernommen. 
Wie sind in Topics Bildergalerien eigentlich hinterlegt? Sind das einfach alle Bilder im Topücs Verzeichnis? 
Momentan wird nur das Hauptbild für den Post übernommen

**Comment by mrbaseman** [comment]
So, mit https://github.com/WBCE/News-with-Images/commit/69e7a63efad5e1b40afe7b3916f6adbdce478ba8 werden Topics Sections (incl. Settings) einigermaßen brauchbar übernommen. Platzhalter, die NWI nicht kennt werden automatisch entfernt, wobei ich mir nicht sicher bin, ob ich alle erwischt habe. 
Es gibt viele Unterschiede im Detail, so dass ein Nutzer, der an den Templates für die Posts Einstellungen vorgenommen hat, nach dem Import vermutlich sowieso nochmal manuell Hand anlegen muss, aber ich würde sagen: Hauptsache die Posts werden übernommen und die wichtigsten Einstellungen passen grob.

**Comment by mrbaseman** [comment]
In https://github.com/WBCE/News-with-Images/commit/3ef86a1a445761a786b6e7be51c3defaf7f89a45 sind noch ein paar Fixes mit drin. Damit kann man es vielleicht belassen
