### ISSUE TITLE
Drag and Drop Sortierung

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/News-with-Images#14]
siehe auch #3

**Comment by mrbaseman** [comment]
ist mit 5ba5614c3711566b6e2c504c2c1c88e1ee02a200 implementiert

**Comment by mrbaseman** [comment]
mir sind noch 2 Kleinigkeiten eingefallen:
- Sortierung muss noch getestet werden, wenn mehrere Sections angelegt sind, funktioniert Drag&Drop dann nach wie vor? (Beide Sections auf gleicher Seite oder beide Sections auf unterschiedlichen Seiten). Im Gegensatz zu den Feldern bei mpForm ist hier die Sortierung "rückwärts", was eine Änderung der Schleife nach sich gezogen hat, bei der ich nicht 100% sicher bin, ob das so funktioniert.
- Drag&Drop Handles ausblenden wenn Sortierreihenfolge nicht auf manuell eingestellt ist (analog zu den Sortierpfeilen, ist nur ne Kleinigkeit, die ich heut Nacht vergessen hatte)

**Comment by instantflorian** [comment]
Der Anfasser für D&D-Sortierung wird auch angezeigt, wenn bei den Einstellungen etwas anderes als benutzerdefinierte Reihenfolge angegeben ist. Im BE wird dann dadurch auch die Reihenfolge geändert, im Frontend (korrekterweise) nicht.
Erwartetes Verhalten wäre mMn, dass bei allen Einstellungen außer "benutzerdefiniert" im BE kein D&D-Anfasser erscheint.

Ach, sehe gerade, das hat sich mit dem Reopen-Kommentar von gerade eben überschnitten.

**Comment by mrbaseman** [comment]
ja, genau. Drag&Drop handles sind mit https://github.com/WBCE/News-with-Images/commit/c5a77f9d77eaa1ba373a5f10f6c6cbed1785b3ee ausgeblendet wenn automatische Sortierung der Posts gewählt wird.

**Comment by mrbaseman** [comment]
Ok, Drag&Drop funktioniert zumindest in meinen Tests auch wenn es mehrere Sections gibt.

**Comment by mrbaseman** [comment]
https://github.com/WBCE/News-with-Images/commit/d9ba2cfb0d57419a804fdc2e75aa3d2109c7bfee implementiert drag&drop für die Gruppen

**Comment by mrbaseman** [comment]
und schließlich haben wir in https://github.com/WBCE/News-with-Images/commit/c8d13ce92ffa5e19dce6e4a5e9bb531d38dfb36f das D&D für die Bilder
