### ISSUE TITLE
Sprachunterstützung

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/News-with-Images#15]
* Sprachdateien FR und IT ergänzen
* generell Sprachdateien überarbeiten, 
* NL Sprachunterstützung

**Comment by mrbaseman** [comment]
Änderung der Variablen von $MOD_NEWS u $MOD_NEWS_IMG

**Comment by webbird** [comment]
Commit https://github.com/WBCE/News-with-Images/commit/63ab25b3b8d7533e1e5464a3d13aec6c91701af9

**Comment by mrbaseman** [comment]
auf die Schnelle maschinell übersetzt und dann mal grob drüber geschaut: https://github.com/WBCE/News-with-Images/commit/50d8f90207469ae25f99cc40dc0e119d17aa170d
IT ist glaub ganz gut, in FR bin ich nicht mehr so sattelfest und NL mehr oder weniger im Blindflug... ursprüngliche Variablen aus altem News-Modul übernommen, aber das macht ja nur einen Bruchteil des ganzen aus.
Was noch fehlt: kontrollieren ob noch wo was hart gecoded ist und eine aussagekräftige Meldung für #18, evtl weitere Übersetzungen für noch ausstehende Implementierungsteile

**Comment by mrbaseman** [comment]
Die Meldung für #18 ist mit https://github.com/WBCE/News-with-Images/commit/ebb628beb38a602555efe627a84992b7737c1af5 implementiert. 
Ich habe auch den Code überflogen und keine hart codierten Strings gefunden, die man noch übersetzen müsste.
Fürs 4.0 Release sollte vielleicht noch jeweils ein Muttersprachler drüber schauen... oder auch nicht...
