### ISSUE TITLE
Update upgrade.php

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#17]
- [x] commenting
- [x] image folder
- [x] move images from pages to media
- [x] german column names

**Comment by mrbaseman** [comment]
upgrade vom klassischen News ist nicht vorgesehen, richtig? Allein der unterschiedliche Modulname macht das wahrscheinlich schon fast unmöglich. Import von einzelnen News Sections ist ja in #13 mit implementiert.
Verschieben von Pages nach Media ist aus Sicht des upgrade Skripts nach wie vor offen, richtig?

**Comment by instantflorian** [comment]
Nein, kein Update von klassischen News, das geht ja in der Tat über den internen Import.
Anpassung an die Veränderung des Bildverzeichnisses ist noch offen, wobei das ja eigentlich nur die ursprüngliche speziell angepasste Kundinnen-Version betrifft.

**Comment by mrbaseman** [comment]
Bilder vom alten zum neuen Pfad verschieben sollte mit https://github.com/WBCE/News-with-Images/commit/469cd7a03ca73518ab0875edda01e4d4419a59b5 gelöst sein. @webbird kannst du mal drüber schauen, ob das so passt?

**Comment by mrbaseman** [comment]
I think this completed, too
