### ISSUE TITLE
Ändern der Galerie

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#18]
Ändert man in den Einstellungen die Galerie (Fotorama oder Masonry), wird mit dem Speichern auch das Markup geändert. Das muss einerseits sein, damit die Galerie auch richtig angezeigt werden kann, andererseits verliert man evtl. eigene Änderungen.

**Comment by mrbaseman** [comment]
Idee aus dem Forum: Vielleicht einfach dem Benutzer einen Hinweis darauf geben, z.B. mit einem JS Popup auf dem onchange event mit einer entsprechend ausführlichen "Sind sie sicher?"-Rückfrage

**Comment by mrbaseman** [comment]
ich hab ein js Popup mit commit https://github.com/WBCE/News-with-Images/commit/ebb628beb38a602555efe627a84992b7737c1af5 implementiert und die Übersetzungen in den Sprachdateien hinterlegt
