### ISSUE TITLE
Gallery images not in database

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#20]
Since the new handling of images (folders per post instead of renaming) gallery images are uploaded, but not stored in the mod_news_img_img table and so they appear neither in the BE nor in the FE. I've already had a glance at the save_post.php, but did not find the reason.

**Comment by webbird** [comment]
Ich wollte ohnehin noch die Spaltennamen in der _img Tabelle ändern, dann mache ich das auf einen Rutsch.

**Comment by mrbaseman** [comment]
Ok, dann warte ich mal noch mit #19 -  Wenn das "normale"  Anlegen von Posts mit Bildern wieder funktioniert, ziehe ich das Kopieren entsprechend nach.

**Comment by webbird** [comment]
Gefixt; im Commit waren in der install.php schon andere Spaltennamen, sonst aber nirgends.
