### ISSUE TITLE
Großvorschau Galeriebilder in Bearbeitungsansicht defekt

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#22]
Jetzt sind die Thumbnails da, aber dafür die Großbilder nicht :(
![2019-04-25_094121](https://user-images.githubusercontent.com/1433754/56718064-5f89a400-673e-11e9-949a-694676e68165.jpg)

**Comment by mrbaseman** [comment]
Das hab ich gestern auch gesehen, war mir aber nicht sicher, ob ich die letzten Änderungen von Bianka komplett in meiner Testumgebung drin hatte

**Comment by mrbaseman** [comment]
war Problem WB_URL vs. WB_PATH
