### ISSUE TITLE
Sortierung und Gruppen / Gruppen-ID

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#23]
Die Zuordnung eines Beitrages zu einer Gruppe hat keinen Einfluss auf die Reihenfolge in der Ansicht. 
Es ist also nicht möglich, Beiträge automatisch nach Gruppen sortiert anzuzeigen, z.B. so:

**Gruppe 1 Überschrift**
Beitrag 1 in Gruppe 1
Beitrag 2 in Gruppe 1
**Gruppe 2 Überschrift**
Beitrag 1 in Gruppe 2
Beitrag 2 in Gruppe 2

Womit sich dann die Frage stellt, wozu die Reihenfolge der Gruppen überhaupt noch dient. 
![2019-04-25_102016](https://user-images.githubusercontent.com/1433754/56721045-5dc2df00-6744-11e9-8239-6b4841020467.jpg)

Die einzige Funktion der Gruppen ist also mMn, eine Filterungsfunktion zu ermöglichen (Aufruf im FE mit Parameter ?g=Gruppen-ID). Dafür sollte die ID dann aber im BE angezeigt werden.

**Comment by mrbaseman** [comment]
ich dachte die Gruppen wären so vorgesehen wie von Dir skizziert. Da fehlt wahrscheinlich noch `group_id` nach `ORDER BY`

**Comment by mrbaseman** [comment]
war nun doch etwas komplizierter, aber mit https://github.com/WBCE/News-with-Images/commit/50acf98a3c5ee33e5021f07a5533f9531c8e647d werden jetzt die Posts zunächst nach Gruppen vorsortiert. 

Diese Vorsortierung widerspricht ein bisschen der sonstigen Sortierung: Sowohl die manuelle Reihenfolge als auch die automatische Sortierung nach Datum oder Post-ID wird aufgebrochen und erstmal in Blöcke der jeweiligen Gruppen aufgeteilt. Erst darin erfolgt dann die im Backend eingestellte Sortierung.

Ist das was man will? Ich würde das so sehen. Wer wirklich eine durchgängige Sortierung nach Datum haben will, soll einfach die Gruppen nicht nutzen. Um dennoch eine Grobsortierung vornehmen zu können, sind ja auch zwei Sections auf einer Seite möglich (und mit News_with_images können ja sogar Beiträge über Section-Grenzen hinweg verschoben werden).

Ich lasse das Thema mal noch offen. Was auch noch fehlt ist Drag&Drop für die Gruppen.

**Comment by mrbaseman** [comment]
Sortierung für Gruppen mittels Drag&Drop ist jetzt auch implementiert. Ich denk dann kann ich dieses Issue auch zu machen. Falls die Grobsortierung nach Gruppen anders gewünscht ist oder auch noch eine Option braucht, bitte das Issue wieder aufmachen oder ein neues erstellen
