### ISSUE TITLE
Fehler beim Kopieren von Seite A auf n-ten Abschnitt auf Seite B

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#24]
Wenn mehrere News-Abschnitte auf einer Seite stehen, und im zweiten (n-ten) Newsabschnitt ein Beitrag durch Kopieren erstellt wird, so wird dieser nicht korrekt erzeugt (Notice: Undefined variable: MOD_NEWS_IMG in /.../view.php on line 340 in der Beitragsübersicht, eine Reihe von Notices und kein Content in der Detailansicht des Beitrages)

**Comment by mrbaseman** [comment]
Im Zusammenhang von #11 was ich als nächstes angehen werde, ändert sich der Kopiercode wahrscheinlich auch nochmal (zwar nicht komplett aber doch in größerem Ausmaß). Aber danke, ich werd die Problematik mehrere NWI-Abschnitte auf einer Seite dabei im Hinterkopf behalten.

**Comment by mrbaseman** [comment]
ist wohl mit https://github.com/WBCE/News-with-Images/commit/cba593e6db13a0dcff329f2bc98dd92cd19fdab9 behoben, zumindest sehe ich das hier beschriebene Problem mit dem aktuellen Stand nicht. Falls das Phänomen bei dir nach wie vor auftritt, bitte Ticket einfach wieder öffnen.

**Comment by instantflorian** [comment]
Nein, leider nicht... siehe Testwebsite, Zugangsdaten stehen im Forum

**Comment by mrbaseman** [comment]
Oh, sorry, muss ich mir nochmal genauer anschauen. Ich glaube die Sections in meinen schnellen Kopiertests waren versehentlich beide auf der gleichen Seite. War schon recht spät gestern Nacht... danke für's unermüdliche Testen.

**Comment by mrbaseman** [comment]
ich hab jetzt einige commits rund ums kopieren gemacht. Die Beiträge sollten jetzt hoffentlich korrekt kopiert werden.

Das beschriebene Problem mit "Notice: Undefined variable: MOD_NEWS_IMG" scheint aber wohl unabhängig vom Kopieren zu sein, sondern immer dann aufzutreten, wenn ein langer Beitrag, bei dem ein Read-More Link eingeblendet werden soll in der zweiten NWI-Section auf der Seite auftaucht. Die Sprachdatei wird beim zweiten Durchlauf nicht neu geladen und die Werte sind irgendwie weg. Ändert man das require_once beim Einbinden der Sprachdatei zu einem schlichten require, dann tuts. 

Da stellt sich aber eine viel allgemeinere Frage, warum das require_once nicht richtig funktioniert. Eigentlich ist die Datei ja bereits eingebunden. Die Sprachvariablen werden im ersten Durchgang in block_contents aus framework/frontend.functions.php geladen. Beim zweiten Durchgang sind sie weg, und das require_once springt nicht mehr an, weil genau diese Datei ja schon mal sogar an der gleichen Stelle geladen wurde. Dass Variablen aus dem vorherigen Durchlauf aufgeräumt wurden ist ein gewünschter Effekt, aber wenn Funktionen nicht verfügbar sind, weil require_once beim zweiten Durchgang nichts mehr lädt, dann ist das ein Problem. Aber das ist ein Problem des Core - und genau das Verhalten haben wir mal anderswo diskutiert, aber den Nebeneffekt des require_once damals nicht mitbedacht. Ich mach noch ein issue für den Core dazu auf.

**Comment by mrbaseman** [comment]
ich hatte vergessen den commit https://github.com/WBCE/News-with-Images/commit/1337ff6d2baea9358f0f2cc622bd6a68631ffb45 hier zu verlinken

**Comment by instantflorian** [comment]
Die Notice: Undefined variable: MOD_NEWS_IMG tritt unabhängig vom Kopieren auf, also auch wenn Beiträge in einem 2. News-Abschnitt auf einer Seite neu angelegt werden (also nicht dorthin kopiert werden).

**Comment by wbEasy** [comment]
mrbaseman schrieb:
> Beim zweiten Durchgang sind sie weg, und das require_once springt nicht mehr an, weil genau diese Datei ja schon mal sogar an der gleichen Stelle geladen wurde. Dass Variablen aus dem vorherigen Durchlauf aufgeräumt wurden ist ein gewünschter Effekt, aber wenn Funktionen nicht verfügbar sind, weil require_once beim zweiten Durchgang nichts mehr lädt, dann ist das ein Problem. 

Wenn Variablen/Arrays im zweiten Durchlauf gelöscht (aufgeräumt) werden, dann ist die naheliegendste Lösung, statt require_once, require zu verwenden.

Wie sieht es mit anderen Modulen aus, die z.B. Dateien mit Funktionen einbinden?
Tritt der selbe Fehler auf, sodass dann die Funktionen nicht mehr zur Verfügung stehen, wenn man von einem Modul mehrere Sections auf der selben Seite hat?

**Comment by mrbaseman** [comment]
Sicher, require wäre eine Lösung, Funktionen innerhalb der includierten Datei müssen mit if(!function_exists()) geschützt werden und das müssen ALLE Module für ALLE Vorkommen von require_once im Frontend umsetzen...

**Comment by wbEasy** [comment]
Meine Frage war, weil ich grade nicht vor der Maschine sitze, ob es bei anderen Modulen zu Problemen führt, wenn Dateien mit Funktionen die über require_once aufgerufen wurden ihre Funktionen verlieren (beim nächsten Durchlauf).
Also nicht theoretisch, sondern praktisch überprüft.

**Comment by mrbaseman** [comment]
Ich habe für News-with-Images einen Fix committed, daher schließe ich dieses Issue.
Die generelle Diskussion ob wir das Verhalten, so wie es momentan implementiert ist, beibehalten wollen, sollten wir in [#417](https://github.com/WBCE/WBCE_CMS/issues/417) führen und nicht hier bei einem speziellen Modul.
