### ISSUE TITLE
Anzeige der Uhrzeit in BE / FE

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#25]
Irgendwas stimmt mit den Uhrzeitangaben noch nicht. Obwohl in den Standard- als auch Profileinstellungen GMT+2 ausgewählt ist, steht in der Beitragsansicht im BE GMT als Startdatum. Wenn ich die Platzhalter [MODI_TIME] | [PUBLISHED_TIME] ergänze, wird im FE die Änderungszeit (MODI_TIME) korrekt als GMT+2 angezeigt,(PUBLISHED_TIME wie im BE als GMT.

**Comment by mrbaseman** [comment]
Ich glaub das war schon im ursprünglichen News etwas verbogen. Da fehlt irgendwo ein ` + TIMEZONE` bei der Ausgabe. 
Zusätzlich gab es noch ein interessantes Phänomen, dass sich das unterschieden hat, je nach dem ob man angemeldet ist oder nicht, da der Benutzer eine eigene Einstllung für die Zeitzone hat. Ich meine der letzte Punkt wäre in WBCE mal global gefixt worden.

**Comment by mrbaseman** [comment]
ich hab mir das angeschaut und bin zum Schluss gekommen, dass die Ausgaben funktionieren, in denen zunächt mit gmdate eine Ausgabe auf GMT bezogen wird, dafür jedoch der Input mit +TIMEZONE korrigiert wird. Die Stellen, an denen einfach date verwendet wird, scheinen wohl nicht das zu tun was man erwarten würde. Daher hab ich das mal in https://github.com/WBCE/News-with-Images/commit/821a647905bb2f77bb11552cc6cdef2c0f29b953 vereinheitlicht. Ich hoffe dass das so jetzt richtige Zeiten in der Ausgabe erzeugt

**Comment by instantflorian** [comment]
Beim Anlegen von Beiträgen wird als Startdatum weiterhin GMT angezeigt, das dann in der Übersicht als GMT+2 erscheint
![2019-04-29_081106](https://user-images.githubusercontent.com/1433754/56878857-6d00a000-6a56-11e9-83fe-38a87cca5c5d.jpg)

**Comment by mrbaseman** [comment]
ok, ich sollte vielleicht zum Testen auch was anderes als GMT als eigene Zeitzone einstellen ;-)
probier mal ob https://github.com/WBCE/News-with-Images/commit/bbbec4aa50282ba41ee1dee1a8fe967d3613651f das Problem jetzt löst
