### ISSUE TITLE
Warnings beim Löschen von ganzen News-Seiten

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#26]
Beim Löschen von ganzen News-Seiten erscheinen Warnings für jedes Beitragsbild: Warning: unlink.../media/.news_img/xyz.jpg): No such file or directory in .../modules/news_img/delete.php on line 43, da scheint noch die alte Verzeichnis-/Bild-Systematik hinterlegt zu sein

**Comment by mrbaseman** [comment]
should be solved by https://github.com/WBCE/News-with-Images/commit/240d29836bda32f909feb60eb9ad2c3e60b1d316

**Comment by instantflorian** [comment]
Fehler tritt weiterhin auf

**Comment by mrbaseman** [comment]
so, jetzt aber mit https://github.com/WBCE/News-with-Images/commit/f1f044b7f6fb4841cbefae253ab794b2fb34eeac wird systematisch aufgeräumt, auch die index.php Dateien und anschließend die Directories

**Comment by instantflorian** [comment]
Fehler tritt weiterhin auf

Warning: unlink(/.../media/.news_img/13/index.php): No such file or directory in /.../modules/news_img/delete.php on line 47

Warning: rmdir(/.../media/.news_img/13): No such file or directory in /.../modules/news_img/delete.php on line 48

für jeden Beitrag

**Comment by mrbaseman** [comment]
ist ein bisschen ein anderer Fall als zuvor, aber mit https://github.com/WBCE/News-with-Images/commit/749cff7631fd12f10fb633211c0c16f86fdf6e96 wird jetzt geprüft, welche Dateien/Verzeichnisse existieren, bevor versucht wird sie zu löschen. Solange keine Bilder zu einem Post hochgeladen werden, dann wird auch das Verzeichnis und die index.php darin nicht angelegt.
