### ISSUE TITLE
Doku / Hilfe

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#27]
Platzhalter, Darstellungsmöglichkeiten usw... Hilfe-Button im BE

**Comment by instantflorian** [comment]
Ist (erstmal) nur auf deutsch. Ich hab gerade keine Idee, wie sich das mit überschaubarem Aufwand auch in anderen Sprachen bereitstellen lässt.

**Comment by mrbaseman** [comment]
Cool, danke!
