### ISSUE TITLE
Ideas for better UI experience

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#3]
- Make news items sortable by drag & drop
- Make gallery images sortable by drag & drop
- Replace single image upload fields by plupload or sth. like that
- list start & end date in news overview

**Comment by mrbaseman** [comment]
- import of complete topics sections?

**Comment by instantflorian** [comment]
hm, this would be not so easy I'm afraid. Topics has more database tables / fields than news, for configuration as well as topic details. 

-------- Ursprüngliche Nachricht --------
Von: Martin Hecht <notifications@github.com> 
Datum:14.04.2019  10:58  (GMT+01:00) 
An: WBCE/News-with-Images <News-with-Images@noreply.github.com> 
Cc: instantflorian <info@meerwinck.com>,Author <author@noreply.github.com> 
Betreff: Re: [WBCE/News-with-Images] Ideas for better UI experience (#3) 

import of complete topics sections?

**Comment by mrbaseman** [comment]
I'll have a look. Anyway we can not import everything, because we don't have all the fancy features. But maybe the most important parts...

**Comment by webbird** [comment]
list start & end date in news overview -> done with issue #9

**Comment by mrbaseman** [comment]
drag & drop for news items -> done with #14 (except for testing and a minor improvement)

**Comment by mrbaseman** [comment]
all of the above listed Drag & Drop features are implemented now, the only thing left are the upload fields for the single images.

In mpform I have enabled selection of multiple files in one upload field. It's not very transparent to the end user, so maybe an explanation is needed (but the method how to select multiple files may depend on the browser; usually it is pressing shift or control on the keyboard plus left mouse button). The $_POST entry is simply an array then. 

Another alternative would be to allow zip files which are uncompressed then on the server side, just like in the /media folder. End users may like this more than some fancy key combination to select files.

 Another Idea would be to offer selecting a folder from the /media area (just like the insert image in ckeditor) - for single images it's less convenient than what we have, but for a whole folder it would be an easy option to copy in a complete gallery from the media folder (note that I would offer to copy files, and not link them, for the reasons already discussed)

**Comment by instantflorian** [comment]
Hm, there are quite a few jquery based multiple file uploaders. I think one of these would be nice. 
https://colorlib.com/wp/jquery-file-upload-scripts/

But the multiupload via one field would be also okay, it just has to be mentioned (and should be supported by all common browsers)

**Comment by mrbaseman** [comment]
Drag&Drop relies on JavaScript. If this is not enabled, moving posts/groups/images is not possible anymore. Should we add a fallback for this situation? i.e. show the move up/down arrows and hide them again by means of JS? I have just commented out the code at the moment, so it can easily be reactivated.

**Comment by mrbaseman** [comment]
answering to myself: https://github.com/WBCE/News-with-Images/commit/e9504ad2b841392a8d4ade1b55c7ae2636efe254 implements the fallback when JS is disabled

**Comment by instantflorian** [comment]
I think we need to think a bit about the 2nd block.
It would be useful if there was the possibility to choose whether to use/show the 2nd block input field in the backend or not. 
Also, there might be the wish to customize the output of the 2nd block as well and/or place the gallery there. But this is probably a lot of effort and has to be done in an upcoming release.

**Comment by mrbaseman** [comment]
maybe just a define('NWI_USE_SECOND_BLOCK', true) in a config.php file, and everything that shows the second block in backend and frontend is enclosed by an if statement?

**Comment by instantflorian** [comment]
+1

**Comment by mrbaseman** [comment]
the NWI_USE_SECOND_BLOCK switch is implemented in https://github.com/WBCE/News-with-Images/commit/ceb0bbb3b445d23b4b92f438165930c426dee436
I have started looking into [jQUery Ajax File Uploader](https://github.com/danielm/uploader) for the drag&drop multiple file upload. The demo works nicely, but integrating it into the module requires a bit of work.

**Comment by mrbaseman** [comment]
the uploader is implemented with https://github.com/WBCE/News-with-Images/commit/cc09062e6c4f5df3304adb421f0fab4a773a3ff8
