### ISSUE TITLE
Beitrag verschieben funktioniert nicht richtig

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#30]
**Über die Gruppenzuordnung im Beitrag:**
Wenn ein Beitrag von der Seite NWI1 zur Seite NWI2 verschoben wird, erscheint der Beitrag zwar sowohl im FE als auch BE in der Übersichtsseite/liste von NWI2, beim Anklicken des Beitrags im Frontend wird dieser jedoch weiterhin auf der Seite NWI1 angezeigt.

**Über Verschieben/Kopieren in der Beitragsübersicht:**
Verschieben erfolgt zwar, endet aber auf leerer Seite mit der Auschrift "Cannot access this file directly"
URL domain.tld/modules/news_img/modify.php?page_id=XX&section_id=YY 
(XX/YY = reale Werte)

Desweiteren tritt derselbe "Zuordnungsfehler" wie beim Verschieben einzelner Beiträge auf.

**Comment by mrbaseman** [comment]
should be fixed by the above commits
