### ISSUE TITLE
Löschen funktioniert nicht

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#31]
Nach der Bestätigung, dass die ausgewählten Beiträge wirklich gelöscht werden sollen:
Parse error: syntax error, unexpected '{' in /.../modules/news_img/delete_post.php on line 40

Fehler tritt sowohl beim Löschen von einzelnen als auch mehreren markierten Beiträgen auf.

**Comment by mrbaseman** [comment]
fixed with the above-mentioned commit
