### ISSUE TITLE
Parameter g=x erzeugt Fatal Error

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#32]
Aufruf einer NWI-Seite mit Parameter g=GROUP_ID, unabhängig davon, ob Gruppe existiert oder nicht:
Fatal error: Uncaught Error: Call to a member function numRows() on null in /.../modules/news_img/view.php:164 
Stack trace: 
#0 /.../framework/frontend.functions.php(228): require() 
#1 /.../framework/frontend.functions.php(339): get_section_content('63') 
#2 /.../framework/frontend.functions.php(405): block_contents(1) 
#3 /.../templates/zonta/index.php(74): page_content(1) 
#4 /.../index.php(68): require('/www/htdocs/w01...') 
#5 /.../pages/nwi.php(8): require('/www/htdocs/w01...') 
#6 /.../short.php(38): include('/www/htdocs/w01...') 
#7 {main} thrown in /.../modules/news_img/view.php on line 164

**Comment by mrbaseman** [comment]
fixed with https://github.com/WBCE/News-with-Images/commit/d9c8008313fb8a59148f6a9a924e08311a5023b4
