### ISSUE TITLE
Aktivieren/Deaktivieren aus Beitragsübersicht heraus

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#34]
Schick wäre noch, analog zu OPF Dashboard oder OneForAll die Umschaltung Aktiv Ja/Nein direkt aus der Übersicht vornehmen zu können, und/oder diese Möglichkeit mit bei den Massenaktionen Verschieben/Kopieren/Löschen zur Verfügung stände.

**Comment by mrbaseman** [comment]
Sollte kein großer Aufwand sein. Knöpfe zum Aktivieren/Deaktivieren in der Übersicht sind 2 längliche Links und eine activate_post.php analog zur delete_post.php... Das bei den Massenaktionen dann noch mit aufzunehmen ist dann glaub auch nur ein paar Zeilen Code. Ich schau es mir heut abend oder am Wochenende genauer an.

Danke auch fürs Testen. Da haben sich ja doch wieder ein paar Bugs eingeschlichen. Ich schätze das sind alles Kleinigkeiten die in wenigen Zeilen zu fixen sind.

**Comment by mrbaseman** [comment]
Noch zu ergänzen:
- massenweise posts aktivieren/deaktivieren über die Checkboxen in der Übersicht (ist in activate_post.php schon vorgesehen)
- evtl. Led-Anzeige wie beim Opf Dashboard? 
- besserer Link Titel, dazu ergänzen der Sprachdateien um "Post aktivieren" und "Post deaktivieren"

**Comment by mrbaseman** [comment]
mit dem gerade verlinkten Commit ist das vollends umgesetzt. Massen-Aktion geht jetzt, auf LED-Anzeige habe ich verzichtet, Link Beschriftung wurde aber verbessert und Sprachdateien ergänzt
