### ISSUE TITLE
Import settings

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/News-with-Images#35]
A nice thing to have would be the possibility to import or copy&paste all settings values from one section to another one. Somehow like assigning a template in topics

**Comment by instantflorian** [comment]
+1, I thought of this already too...

**Comment by mrbaseman** [comment]
Especially when importing several sections to NWI one might want to impose the same settings (or re-assign NWI defaults again)

**Comment by mrbaseman** [comment]
implemented with 3.7.16
