### ISSUE TITLE
Beim Anklicken von "Beitrag verfassen" erscheint Fehlermeldung

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#37]
"Abschnitt Nicht gefunden"

Nicht immer, aber manchmal, Es scheint etwas damit zu tun zu haben, wenn mehrere Tabs geöffnet sind und man auf anderen Tabs im BE etwas macht.
Ein konkretes Muster ist aber leider nicht zu erkennen
![2019-05-18_070806](https://user-images.githubusercontent.com/1433754/57964808-bf3d2e80-793b-11e9-9866-131eb864496a.jpg)

**Comment by instantflorian** [comment]
ist eben auch 2x bei Gruppe anlegen aufgetreten

**Comment by mrbaseman** [comment]
hier bin ich noch nicht ganz durchgestiegen. Die Fehlermeldung kommt jedenfalls aus dem [admin-Skript](https://github.com/WBCE/WBCE_CMS/blob/master/wbce/modules/admin.php#L79), wo [get_section_details](https://github.com/WBCE/WBCE_CMS/blob/master/wbce/framework/class.admin.php#L352) aufgerufen wird. Dabei spielt die $section_id eine Rolle. 
Könnte sein, dass das was ähnliches wie in #39 ist, dass aus dem Modul heraus manche Variablen (in diesem Fall die $section_id) nicht geändert werden dürfen. Da die in manchen Fällen (add_post.php, add_group.php, modify_settings.php) als idkey übergeben und dann aufgeelöst werden, könnte das die Ursache sein. 
Leider kann ich es nicht reproduzieren, aber vielleicht hilft ja commit https://github.com/WBCE/News-with-Images/commit/5067228b2f2d004f69a5f94a090824278aadf5a8

**Comment by mrbaseman** [comment]
Hab ich richtig geraten und der Fehler ist nicht mehr aufgetreten? Sollte er doch nochmal zu beobachten sein, versuch mal genau zu beschreiben was du in welcher Reihenfolge in den verschiedenen Browsertabs gemacht hast.

Ähm, was mir gerade einfällt: wenn du in der Zwischenzeit für die Tests zu #39 die aktuelle Section aus einem anderen Tab heraus gelöscht hast, dann hat die Meldung durchaus ihre Berechtigung...

**Comment by instantflorian** [comment]
>Hab ich richtig geraten und der Fehler ist nicht mehr aufgetreten? 
>Sollte er doch nochmal zu beobachten sein, versuch mal genau zu 
>beschreiben was du in welcher Reihenfolge in den verschiedenen 
>Browsertabs gemacht hast.
>
Ich hatte gestern und heute auf verschiedene Weise versucht, den Fehler 
zu reproduzieren, also schnell hintereinander neue Beiträge zu 
erstellen, vorher auf einem anderen Tab was gemacht, im FE Seiten 
aufgerufen / neu geladen etc., wobei ich gestern kein Muster feststellen 
und heute den Fehler nicht reproduzieren konnte. Deshalb gehe ich davon 
aus, dass das Problem gelöst ist.
>
>
>Ähm, was mir gerade einfällt: wenn du in der Zwischenzeit für die Tests 
>zu #39 <https://github.com/WBCE/News-with-Images/issues/39> die 
>aktuelle Section aus einem anderen Tab heraus gelöscht hast, dann hat 
>die Meldung durchaus ihre Berechtigung...
>
Das war nicht der Fall, d.h. die Section existierte ganz normal und beim 
erneuten Anklicken von Beitrag / Gruppe hinzufügen in der selben Section 
kam es ja dann zum erwarteten Verhalten, sprich Eingabefelder für 
Beitrag bzw. Gruppe.

**Comment by mrbaseman** [comment]
Ok, danke, dann wird es wohl was mit der Verwendung der $section_id Variablen zu tun haben.
