### ISSUE TITLE
Array to string conversion beim Löschen

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#39]
Notice: Array to string conversion in /.../framework/functions.php on line 1136

Tritt nur beim Löschen von NWI-Seiten auf, sonst nicht. Scheint doch etwas mit dem Modul zu tun zu haben, auch wenn's aus framework.php kommt.

**Comment by mrbaseman** [comment]
Welche WBCE Version ist denn das bzw was steht auf Zeile 1136?

**Comment by instantflorian** [comment]
Aktuelle 1.4 Beta, functions.php vom 13.04.
`    $directory = WB_PATH . PAGES_DIRECTORY . $link;`
