### ISSUE TITLE
Unschöne Darstellung der Newsübersicht mit Argos Reloaded BE-Theme

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#43]
![2019-05-22_070949](https://user-images.githubusercontent.com/1433754/58148858-ae086080-7c60-11e9-890d-9470d8751ce0.jpg)

**Comment by mrbaseman** [comment]
fixed with https://github.com/WBCE/News-with-Images/commit/057b680d6eff8004b242de18e2150c02222bec9a ?
