### ISSUE TITLE
Mengenaktionen funktionieren nicht in WB 2.12.1

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#45]
Kopieren:
There was an uncatched exception
Call to undefined function page_filename()
in line (114) of (/modules/news_img/copy_post.php):

Importieren:
There was an uncatched exception
Call to undefined function page_filename()
in line (185) of (/modules/news_img/import.php):

Löschen:
There was an uncatched exception
Call to undefined function rm_full_dir()
in line (78) of (/modules/news_img/delete_post.php):

Verschieben (in Gruppe):
There was an uncatched exception
Call to undefined function change_mode()
in line (171) of (/modules/news_img/functions.inc.php):

**Comment by mrbaseman** [comment]
hmm... ok, with the functions we can just copy the ones available in WBCE into functions.inc.php and enclose them with an `if(!function_exists('...')){...}`

**Comment by mrbaseman** [comment]
https://github.com/WBCE/News-with-Images/commit/82b2c5d007fd0f3cf3682bb7644c14451134f31b probably is the better solution. Hope it works, I can't test ATM.

**Comment by instantflorian** [comment]
I can't test either, due to #47

**Comment by mrbaseman** [comment]
...which I believe should be fixed by the above referenced commit, if not I'll look into this again in the evening

**Comment by instantflorian** [comment]
you're right, both issues are fixed. Thanks.

**Comment by mrbaseman** [comment]
Cool. It seems the mechanism to load the framework has been changed slightly in recent WB versions.
