### ISSUE TITLE
Featurewunsch: Beiträge aus Listing ausnehmen

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#48]
Dieser Featurewunsch betrifft auch das dazugehörige Anynews.

Es soll möglich sein, Beiträge zu markieren, die bei einer Auflistung via Anynews ausgenommen werden sollen. 

Erfordert: 
* Checkbox in Listing
* Checkbox in Beitragsdetails
* Datenbankspalte

**Comment by mrbaseman** [comment]
vielleicht implementiert man es als allgemeine Flags, von denen es mehrere für unterschiedliche Zwecke geben kann, beispielsweise Sichtbarkeit auf unterschiedlichen Seiten die jeweils NIA-Droplets enthalten

oder: Man erweitert Gruppen derart dass mehrere Gruppen zugewiesen sein können (ähnlich wie in Linux sekundäre Grupppen) von denen eine dann für die Sichtbarkeit in NIA  steht.

**Comment by webbird** [comment]
https://github.com/WBCE/news_img_anywhere/issues/2

**Comment by webbird** [comment]
@mrbaseman: Allgemeine Flags (oder auch Hashtags) finde ich grundsätzlich eine sehr gute Idee, damit könnte man auch leicht Beiträge in Beziehung setzen, auch über Gruppen oder sogar Abschnitte hinweg. Ich könnte mir allerdings vorstellen, dass das schwierig zu überblicken ist, wenn man viele Gruppen und darin viele Beiträge hat. 

"Wenn Gruppe = A und Beitragsflag = Y und Seite = Z dann nicht anzeigen"...

**Comment by webbird** [comment]
Hm, wie wäre es denn erst mal mit allgemeinen Flags (wobei man dann überlegen müßte, was man innerhalb NWI damit anfängt; derzeit wären die ja quasi nur für Anynews), und bei Any gibt's einen Parameter "skipflags", bei dem man dann eine Liste von Flags angeben kann, die man ausnehmen will?

Im NWI würde ich da erst mal eine Textarea einbauen, 1 Flag pro Zeile. Kann man später immer noch aufhübschen.

**Comment by webbird** [comment]
Vielleicht sollte man Flags auch einfach getrennt von den Beiträgen verwalten, analog Gruppen. Beim Erstellen eines Beitrags kann ich dann die Flags anhaken, die verknüpft werden sollen. Macht vielleicht mehr Sinn als "Freitext", weil man sich dann nicht vertippen kann.

**Comment by webbird** [comment]
Ui. Tolle Idee. Gibt's ja schon.

**Comment by webbird** [comment]
Zur Info, habe meine 3 letzten Kommentare gelöscht.

Man kann ja im aktuellen NWI schon Stichworte verwalten (werden die eigentlich schon genutzt?), wenn man die jetzt noch mit Beiträgen verknüpfen könnte, wäre das Ziel doch im Prinzip schon erreicht.

**Comment by webbird** [comment]
Ich habe gerade Version 4.1.0 ge-push-t. Da sind noch ein paar Punkte offen, z.B. habe ich die Sprachstrings nur für DE und EN eingetragen und noch nichts in die Doku geschrieben. Zudem ist die Darstellung der verfügbaren Tags beim Bearbeiten eines Beitrags sicherlich noch schöner zu lösen, dafür fühle ich mich aber nicht berufen. ;)

Was funktionieren sollte:
* Upgrade
* Neuinstallation
* Deinstallation
---> neue Tabellen mod_news_img_tags und mod_news_img_tags_posts

* Tags anlegen / ändern / löschen
* Tags Beiträgen zuordnen und auch wieder entfernen

Nutzung der Tags derzeit nur über NIA; die Änderungen pushe ich auch gleich.

**Comment by webbird** [comment]
Featurewunsch als solcher ist implementiert, daher schließe ich den Issue. Wenn noch jemand die Darstellung aufhübschen will, immer gern. Weitere Wünsche bitte als eigene Issues.
