### ISSUE TITLE
Trennung Code und Content

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#49]
Momentan sind die Scripten noch die alte Mixtur aus PHP und HTML, das würde ich mit dem nächsten Major Release gern auf Templates umbauen. Twig.

**Comment by instantflorian** [comment]
+1. Das fände ich auch gut.

**Comment by wbEasy** [comment]
Ist es beabsichtigt, dieses Modul zu WB CMS kompatibel zu halten?
In WBCE haben wir eine fortgeschrittene Schnittstelle zu Twig, die sehr viel Arbeit abnimmt, die es aber in WB nicht gibt.
Sollte eine Kompatibilität nicht angestrebt werden, kann ich einen Teil der Umbaut auf Twig für dieses Modul übernehmen.

Christian

**Comment by mrbaseman** [comment]
Hi Christian, 

ja, das Modul soll auch unter WB lauffähig sein. Die Erweiterung "with Images" stammt aus einer Auftragsentwicklung für WB, die webbird in Abstimmung mit ihrer Kundin hier als Basis zur Verfügung gestellt hat. Da kam dann zwar allerlei mit dazu, aber es wäre unfair der Kundin gegenüber, wenn die Weiterentwicklung dessen was sie finanziert hat auf ihrer Platform nicht mehr lauffähig wäre.

**Comment by wbEasy** [comment]
Ach so. Schade.

**Comment by instantflorian** [comment]
Ähm, nein, ganz so ist es nicht, siehe Posts im internen Bereich
https://forum.wbce.org/viewtopic.php?pid=23685#p23685
https://forum.wbce.org/viewtopic.php?pid=24185#p24185

**Comment by mrbaseman** [comment]
Ach so. Dann hatte ich es nicht ganz richtig in Erinnerung. Ich weiß aber dass es auch in der WB Nutzergemeinde Interesse an dem Modul gibt.

**Comment by wbEasy** [comment]
Die können gerne auf WBCE umsteigen. ;-P

**Comment by wbEasy** [comment]
OK, zurück zum Sachlichen, 
ich kann mich dessen gerne annehmen.
Ich würde das Backend Layout an das Layout vom Modul "Sitemap" anlehnen, welches responsive und tabellenlos ist.

**Comment by webbird** [comment]
Man kann auch auf Twig verzichten und PHP-Templates machen, das mache ich in der Regel bei allen Modulen, die Cross-CMS-fähig sein sollen.

**Comment by webbird** [comment]
Für modify.php begonnen ohne Template Engine.

**Comment by webbird** [comment]
Erledigt für modify_post.php

**Comment by mrbaseman** [comment]
...fehlt noch ein `git add templates/default/modify_post.phtml` :)

**Comment by webbird** [comment]
Nee, ich war mit "erledigt" etwas früh dran. ;)

**Comment by webbird** [comment]
Ich hatte heute einen äußerst skurrilen Bug im WinMerge, dadurch sind offenbar ein paar Änderungen wieder rückgängig gemacht worden. Betrifft z.B. den $group_id_key in der modify.phtml. Das hatte ich schon korrigiert, nun ist es wieder drin. :/

**Comment by webbird** [comment]
Erledigt für modify_group.php

**Comment by mrbaseman** [comment]
hab noch zwei Korrekturen für modify_post beim Anlegen eines neuen leeren Beitrags eingechecked https://github.com/WBCE/News-with-Images/commit/7525b7fedac37b2e94d25fe6732d2c6ce894ead5

**Comment by mrbaseman** [comment]
in [save_post.php Zeiile 300](https://github.com/WBCE/News-with-Images/blob/master/save_post.php#L300) geht irgendwas durcheinander wenn man einen neuen Beitrag anlegt und lediglich einen Titel eingibt. Kann es sein dass die schließende Klammer von Zeile 299 ein paar Zeilen weiter runter bis zur nächsten schließenden Klammer muss?

**Comment by webbird** [comment]
Danke. Schau ich mir an.

**Comment by webbird** [comment]
Speichern eines Beitrags nur mit Titel funktioniert bei mir, abgesehen von dem Testoutput, weil ich da noch am Übernehmen existierender Bilder arbeite. Bitte nochmal testen, wenn ich meine letzten Änderungen hochgeladen habe.

**Comment by mrbaseman** [comment]
Ja, die textarea, die in Zeile 300ff ausgegeben wird meine ich. das `exit` in dem Testoutput verhindert aber leider auch dass man den Beitrag speichern kann, zumindest wenn kein Beitragsbild hochgeladen wird.

**Comment by webbird** [comment]
Ich bin da ja auch noch gar nicht fertig.

**Comment by webbird** [comment]
work in progress: view.php
