### ISSUE TITLE
Stichworte beim Kopieren / Verschieben

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#50]
a) Beitrag hat Stichwortzuordnung und wird in dem selben NWI-Abschnitt kopiert
Denkbares / Erwartetes Verhalten: Stichwortzuordnungen werden mitkopiert
Tatsächliches Verhalten: Stichwortzuordnung beim kopierten Beitrag fehlt

b) Beitrag hat Stichwortzuordnung und wird zu anderer NWI-Section verschoben oder kopiert
Denkbares / Erwartetes Verhalten: Stichworte werden in Zielabschnitt kopiert und Stichwortzuordnungen bleiben beim Beitrag erhalten
Tatsächliches Verhalten: Stichworte fehlen komplett (also auch keine Auswahl)

Beim Kopieren eines Beitrages würde ich jetzt davon ausgehen, dass alle beitragsspezifischen Angaben mit kopiert werden. Zumindest beim Kopieren innerhalb des selben Abschnitts.
Beim Verschieben/Kopieren zwischen unterschiedlichen Abschnitten ist es komplexer. Einerseits kann ich mir vorstellen, dass Benutzer enttäuscht sind, wenn sie mühsam eine Stichwortliste erarbeiten und diese dann beim Verschieben oder Kopieren eines Beitrags in eine andere Section nicht erhalten bleibt. Andererseits wird die Gruppe auch nicht mitkopiert/mitverschoben. Hm.

**Comment by mrbaseman** [comment]
Bei den Gruppen ist es jedenfalls so dass die lokal zu jedem Abschnitt sind. Man kann aber im Zielabschnitt eine entsprechende Gruppe anlegen und den Beitrag dann dort hinein kopieren. 

Bei den Tags hat man das gleiche Problem: man müsste erst das Tag kopieren, wenn es in der Ziel Section noch nicht existiert und bekommt wegen auto_increment dort eine andere Id. Dann müsste man die Tag Ids "übersetzen"

**Comment by webbird** [comment]
a) würde ich umsetzen, b) erst mal nicht. 

Bei b) gibt es ja weitere Überlegungen, z.B. ob der Anwender überhaupt *will* dass die Tags mitgenommen werden. Ist ja nicht zwangsläufig so. Also müßte man ihm per Checkbox die Möglichkeit geben, Tags mitzunehmen oder eben nicht.

**Comment by mrbaseman** [comment]
Nur mal als Idee zum drüber Nachdenken:

Vielleicht würde es einfacher werden wenn die Tags global wären und nicht an der jeweiligen Section hängen würden. 

Andererseits würde man dann beim Tags anlegen/löschen von verschiedenen Sections auf die gleichen Daten zugreifen, was uns womöglich mehr Probleme mit Zugriffsrechten einbringt als man mit dem Ansatz erschlagen würde.

**Comment by instantflorian** [comment]
Wiederum andererseits kann WBCE 1.4 ja mit Hybridmodulen umgehen, sprich ein Modul kann sowohl Seitenmodul als auch Admintool sein. Die globale Verwaltung der Stichworte könnte folglich mittels eines integrierten Admintools realisiert werden.

**Comment by webbird** [comment]
Ich persönlich finde es sinnvoll, sie an die Section zu hängen, aber ich bin offen gesagt kein Nutzer von News- oder Blogmodulen. Man könnte aber ein "Tags kopieren" einbauen, analog zu den anderen Kopierfunktionen.

Edit: Mit einer kleinen Änderung der Datenbankstruktur kopiert man auch nicht die Tags, sondern setzt nur Beziehungen, womit auch "globale Tags" möglich wären. (SectionID 0 oder -1)

Da der aktuelle Master noch nicht freigegeben ist, könnte ich das noch umbauen, nur die Testinstallationen müßte man dann von Hand bereinigen.

**Comment by webbird** [comment]
![2019-07-10 18_44_51-WBCE»Verwaltung-Seiten](https://user-images.githubusercontent.com/147354/60987950-f3810a00-a342-11e9-8911-da194f3b036d.png)

**Comment by mrbaseman** [comment]
vielleicht sollten wir beim Anlegen/Löschen von globalen Tags noch abfragen ob der am Backend angemeldete Benutzer in der Admin-Gruppe ist. Also sowas wie 

`if($admin->get_post('global_tag') == 'on' && in_array(1, $admin->get_groups_id() ))` in [save_tag.php](https://github.com/WBCE/News-with-Images/blob/master/save_tag.php#L57). 

Jeder sollte die globalen Tags in den Posts verwenden können, aber es sollte nicht jeder globale Tags löschen können, die andere vielleicht in anderen Sections schon verwenden. Beim Löschen entsprechend wenn die hinterlegte Seciton_id 0 ist dann nur löschen wenn der User in der Admin-Gruppe ist. Beim Anlegen ist es vielleicht nicht so kritisch, aber wenn der Nutzer es dann nicht löschen kann, dann wäre es ungeschickt wenn er es anlegen könnte.

**Comment by webbird** [comment]
Gute Idee!

**Comment by mrbaseman** [comment]
Fürs Bearbeiten der globalen Tags gilt das gleiche und das ist glaub ich mit dem Anlegen zusammen im gleichen Code. Den Bearbeiten-Stift und das Kontrollkästchen zum Anlegen von neuen globalen Tags sollte man dann der Vollständigkeit halber auch ausblenden wenn der User kein Admin ist.

**Comment by webbird** [comment]
Hab ich schon. ;)

**Comment by webbird** [comment]
So, Kopieren mit und ohne Tags habe ich bei mir lokal schon mal drin, ich committe das aber erst, wenn auch das Verschieben inkl. Tags drin ist. Es gibt dann entsprechende Einträge im Dropdown, also "kopieren", "kopieren inkl. Tags", "verschieben", "verschieben inkl. Tags".

**Comment by webbird** [comment]
Sollte erledigt sein. Ggfs. später neuen Issue aufmachen.
