### ISSUE TITLE
Tabelle für Tags wird nicht richtig angelegt

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/News-with-Images#51]
Nach einer Neuinstallation des Moduls schlägt das Anlegen neuer Tags mit der Fehlermeldung Table '(TABLE_PREFIX)mod_news_img_tags' doesn't exist fehl. Offenbar schlug bei der Installation das Anlegen der Tabelle mit den Constraints fehl.

Was genau schief ging weiß ich noch nicht, versuch ich aber rauszufinden.

**Comment by webbird** [comment]
Hängt bestimmt irgendwo an der Reihenfolge.

**Comment by mrbaseman** [comment]
hab mal ein    `trigger_error($database->get_error());` eingebaut und dann kommt:
`Key column 'section_id' doesn't exist in table in .../modules/news_img/install.php on line 101,`

**Comment by webbird** [comment]
Okay gefunden danke.

**Comment by mrbaseman** [comment]
fast. Die Tabelle wird jetzt angelegt, aber wenn man ein anderes TABLE_PREFIX hat, dann kommt
PHP Fatal error:  Uncaught Error: Call to a member function numRows() on null in .../modules/news_img/modify.php:88
```
diff --git a/modify.php b/modify.php
index bf762e5..363814a 100644
--- a/modify.php
+++ b/modify.php
@@ -76,9 +76,9 @@ $order = new order(TABLE_PREFIX.'mod_news_img_posts', 'position', 'post_id', 'se
 $order->clean($section_id);
 
 $query_posts = $database->query(sprintf(
-    "SELECT *, (select count(`post_id`) FROM `wbce_mod_news_img_tags_posts` AS t2 WHERE t2.post_id=t1.post_id ) as tags " .
+    "SELECT *, (select count(`post_id`) FROM `%smod_news_img_tags_posts` AS t2 WHERE t2.post_id=t1.post_id ) as tags " .^M
     "FROM `%smod_news_img_posts` AS t1 WHERE `section_id` = '$section_id' ORDER BY `$order_by` DESC",
-    TABLE_PREFIX
+    TABLE_PREFIX, TABLE_PREFIX^M
 ));
```

**Comment by webbird** [comment]
Arghl

**Comment by webbird** [comment]
Ist erledigt
