### ISSUE TITLE
Undefined variable: importable_sections 

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/News-with-Images#52]
Notice: Undefined variable: importable_sections in .../modules/news_img/templates/default/modify.phtml on line 126
erscheint im Backend - weiß nicht ob das eine Altlast von mir ist, jedenfalls auf der Installation habe ich ansonsten kein News, kein Topics, keine andere NWI Section. Da muss man halt vielleicht einen Leerstring o.ä. vordefinieren.

**Comment by mrbaseman** [comment]
das taucht nur auf, wenn die Section leer ist, also wenn Import sowieso **nicht** möglich sein sollte. Ist die Section leer und Import sollte möglich sein, aber es gibt keine Quell-Section, wird korrekterweise nichts angezeigt, auch keine Notice.

**Comment by webbird** [comment]
Füge mal in der modify.php ein:

// ... else find importable items from other sections
} else {
    $importable_sections = 0;
    // count groups

**Comment by mrbaseman** [comment]
nee, ganz oben, z.B. nach `$posts = array();`
in dem else-Zweig wird die Variable ja weiter unten gesetzt, aber in der ersten Hälfte vom if-Konstrukt wird sie nicht gesetzt.

**Comment by webbird** [comment]
Ist erledigt
