### ISSUE TITLE
Löschen von Beiträgen schlägt fehl wegen IDKEY

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/News-with-Images#53]
aus der Übersicht heraus kann man nicht mehr einzelne Sections mit dem Kreuzchen löschen. Über die Massenaktion (angehakte Sections, Markierte Beiträge löschen, weiter und auf der Folgeseite Bestätigen) geht es

**Comment by mrbaseman** [comment]
du hast bei der Trennung von Code und Layout $post_id_key als $post['id_key'] in $posts mit reingepackt, aber nur in der ersten Hälfte der Ausgebe für die Beiträge. Gegen Ende sind noch ein paar Vorkommen von $post_id_key im modify.phtml übrig geblieben.

**Comment by webbird** [comment]
Argh... und ich dachte noch: Mußt gleich nochmal den Suchen&Ersetzen-Lauf starten...

**Comment by webbird** [comment]
Ist erledigt
