### ISSUE TITLE
Weitere Verwendung der Tags

### ISSUE THREAD

**Issue by mrbaseman** [WBCE/News-with-Images#54]
momentan werden Tags ausschließlich für NIA verwendet. Man könnte sie aber auch

- [x] im Frontend mit anzeigen
- [ ] den Keywords für die Seite hinzufügen (müsste glaub ich über die Insert-Klasse inzwischen recht einfach möglich sein)
- [ ] der internen Suche vor die Füße werfen dass man nach den tags suchen kann (ist nicht so ganz einfach weil man da die Tags und Tag Ids und die posts irgendwie mit collapse zuasmmenführen muss, sollte aber theoretisch machbar sein)

**Comment by webbird** [comment]
- [x] Wenn die Stichworte im FE angezeigt werden, beim Anklicken eine Liste von News mit dem gleichen Stichwort anzeigen

**Comment by instantflorian** [comment]
ja! Bitte! Das wäre fein, denn dann hätte NWI wirklich Blog-Potenzial.

**Comment by webbird** [comment]
Gleich nett mit Farbverlauf? :) Also erstes Stichwort dunkelblau, nächstes etwas heller...

Wobei man dann Stichworte auch priorisieren können müßte.

Auch nett: Tagwolke.

**Comment by instantflorian** [comment]
So weit würde ich gar nicht gehen, Tagclouds sind auch eigentlich schon 
wieder aus der Mode. Ich dachte da halt an den Ausbau des 
Blogmenü-Moduls, sodass eben nicht nur nach Veröffentlichungsdatum und 
Gruppen, sondern auch Stichworten Übersichtsseiten generiert werden 
können. Die Stichworte schlicht und ergreifend als Liste. Die 
unterschiedliche Priorisierung könnte sich höchstens aus der Häufigkeit 
der Verwendung des jeweiligen Stichworts automatisch ergeben und in 
jeweiligen CSS-Klassen niederschlagen, dann kann jede*r selbst 
entscheiden, ob und wie das genutzt wird.

**Comment by mrbaseman** [comment]
ja, ich bin auch dafür das Modul nicht allzu umfangreich zu machen. Neue nützliche Features ja, aber wenn sie zu umfangreich und komplex werden geht das wieder an der angedachten Zielgruppe vorbei

**Comment by mrbaseman** [comment]
Vorschlag: Packen wir die Tags zur Anzeige in der Beitragsschleife (und in der Beitragsansicht) in einen Platzhalter rein? Dann ist es konfigurierbar ob und wo sie angezeigt werden sollen.

**Comment by webbird** [comment]
Ok

**Comment by webbird** [comment]
Jetzt müßte man aber "eigentlich" auch noch anhaken können, ob ein Stichwort im FE angezeigt werden soll oder nicht. Wenn ich z.B. Stichworte wie "skip_on_page_25" verwende, möchte ich die ja eher nicht in der Stichwortliste sehen.

**Comment by mrbaseman** [comment]
Auch wieder wahr. Oder bestimmte Tags (z.B. die nicht mit einem Buchstaben beginnen) werden grundsätzlich nicht im Frontend dargestellt und dienen dann genau diesem beschriebenen Zweck.

**Comment by instantflorian** [comment]
Denkbar wäre sonst auch noch, den Tag-Output mit einer eindeutigen CSS-Klasse/ID zu versehen, z.B. nwitag42 (42 = ID des Tags), dann kann man die ungewollten per CSS ausblenden.

**Comment by webbird** [comment]
"Problem" ist noch, dass das Tag jetzt (erst mal) im Code hartverdrahtet erzeugt wird. Aber für den Anfang...

**Comment by webbird** [comment]
![2019-07-15 11_38_43-WBCE - Aktuelles](https://user-images.githubusercontent.com/147354/61207346-29ccd980-a6f5-11e9-8724-f405cabdc3cf.png)

Offenkundig hatte ich gerade den Import aus Topics getestet. Ich habe die ID in der Ausgabe mit drin, weil ich auch "skip" und "tags" getestet habe. Die Darstellung des Tags ist in der frontend.css hinterlegt.

`<span class="mod_nwi_tag" id="mod_nwi_tag_21_0">topic_21</span>`

21 ist hierbei die ID des Posts, 0 die fortlaufende Nummer des Tags (0-basiert). Statt dessen oder zusätzlich die TagID zu benutzen ist ja kein Aufwand.

**Comment by webbird** [comment]
Das Verlinken der Tags ist jetzt äußerst unschön in der view.php eingebaut; das ziehe ich gerade, wenn ich die view.php überarbeite. Die hat's wirklich nötig. Aber ich hab's mal eben schnell reingebaut, damit man mal gucken kann, wie es aussehen könnte.

**Comment by webbird** [comment]
Achtung neuer Branch 4.1.0! Ich wollte die Tag-Funktionen von der Geschichte mit den Bildern trennen und hab daher nochmal zurückgerudert. Wenn wir eine funktionierende 4.1.0 haben würde ich den master-Branch gern darauf zurücksetzen und dann für die Bilder einen neuen machen.

**Comment by webbird** [comment]
@mrbaseman "(müsste glaub ich über die Insert-Klasse inzwischen recht einfach möglich sein)"

Kannst Du mir da einen Schubs geben?

**Comment by mrbaseman** [comment]
Da im Kommentar ist dokumentiert wie das funktionieren müsste:
https://github.com/WBCE/WBCE_CMS/blob/master/wbce/framework/Insert.php#L303-L310

Mit der Insert-Klasse hat sich @WebDesignWorx eingehender beschäftigt, aber das ganze ist eng verzahnt mit dem OpF Dashboard. Sprich: wenn's nicht so wie gedacht funktioniert, müssen wir beide schauen, wer von uns beiden thematisch näher dran ist.

**Comment by webbird** [comment]
Danke, teste ich mal.

**Comment by webbird** [comment]
Okay, keywords-META ersetzen wäre einfach, aber man will ja erweitern, und dafür fehlen IMHO Methoden. Die in NWI einzubauen halte ich für zu kurz gesprungen, daher stelle ich das mal zurück.

**Comment by mrbaseman** [comment]
Ich schau mal ob ich das auf die Schnelle in der Insert Klasse entsprechend erweitert bekomme. Um von Ersetzen auf Anhängen umzustellen braucht es ja nicht viel. Man muss eben ein neues Flag einführen und das an den passenden Stellen durchreichen.

**Comment by mrbaseman** [comment]
so, anhängen geht jetzt mit https://github.com/WBCE/WBCE_CMS/commit/2213a410874a60eb6fb6911658bbdae54faec63a wie folgt:
```
I::insertMetaTag(array (
  "setname" => "keywords",
  "name"    => "keywords",    
  "content" => "Dieses, Jenes, Welches, Irgendwas",
  "append"  => ", "
)); 
```
mit `append` gibt man den Trennstring an, mit dem das zusammengekleistert werden soll, sofern schon ein entsprechendes Metatag da ist. Das müsste mit allen Meta-Tags gehen, also auch mit Description und, naja, bei Refresh  könnte man z.B. an die Weiterleitungsurl auf diese Weise einen Querystring noch mit dranhängen.

**Comment by webbird** [comment]
Super!

Am Screenshot hier 
https://forum.wbce.org/viewtopic.php?pid=27994#p27994
kann man allerdings erkennen, dass das eventuell nicht so ganz sinnvoll ist... Ist kein technisches Problem, aber ein Tag kann halt auch ein Satz oder sowas sein.

**Comment by webbird** [comment]
Da will man doch jetzt sicher eine Einstellmöglichkeit für haben, gell? Im erweiterten Modus.

Edit: Wenn man's ganz weit treiben will, pro Tag einstellbar...

**Comment by mrbaseman** [comment]
Irgendwo hatten wir auch mal die Idee die Tags unterschiedlich zu behandeln, je nach dem welche Zeichen sie enthalten (z.B. welche die mit Unterstrich beginnen werden nur fürs NIA zur Filterung der Beiträge benutzt aber nicht im Frontend angezeigt, welche mit # werden verlinkt oder so ähnlich). Ich weiß jetzt grad nicht wie viel davon umgesetzt ist oder ob wir das wieder verworfen haben, aber vielleicht fällt uns in der Richtung noch was Elegantes ein?

**Comment by webbird** [comment]
Umgesetzt ist da rein gar nichts. Könnte für den Benutzer im Backend ziemlich kompliziert werden. Ich tendiere dazu, das jetzt erst mal so "einfach" zu belassen und dann in der Praxis zu sehen, was evtl. noch Sinn macht, bzw. auf Anforderungen aus der Community zu warten.
