### ISSUE TITLE
Vorhandene Bilder mehrfach verwenden

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#55]
Um Beitrags- und Galeriebilder mehrfach verwenden zu können, ist zum einen eine Änderung der DB-Struktur erforderlich, zum anderen paßt dann die Verzeichnisstruktur nicht.

Bitte um Diskussion / Meinungen zu dem Feature.

**Comment by mrbaseman** [comment]
Ich würde die Bilder eher kopieren. Dann hat man kein Problem damit wenn die Quellsection gelöscht wird bzw. Bilder dort getauscht/gelöscht werden. 

Man könnte einen Medienbrowser integrieren um bereits vorhandene Bilder zur Auswahl anzubieten. Vielleicht kann man das ckeditor Plugin zur Bildauswahl dafür mit verwenden bzw. dieses kopieren. 

Das so ausgewählte Bild würde ich aber kopieren und  so weiter behandeln als wäre es neu hochgeladen worden.

**Comment by webbird** [comment]
Ich würde es für sinnvoll halten, folgende Änderungen vorzunehmen:

* Das Preview-Bild wird genauso behandelt wie die Galerie-Bilder, das heißt es wird 
  * in die Tabelle *_img_img eingetragen
  * in das gleiche Unterverzeichnis gelegt wie die anderen (.news_img/<PostID>)
  * eventuell auch größentechnisch gleich behandelt (da bin ich noch unsicher)
* In die Tabelle *_posts wird in die Spalte "image" nur noch die ID des Bilds eingetragen, nicht der Name
* eventuell kann man das Preview-Bild in der Tabelle *_img_img auch noch markieren, so dass es nicht in der Galerie auftaucht

Jetzt könnte man entweder die Verzeichnisstruktur ganz weglassen, oder wir hinterlegen in *_img_img auch noch den ursprünglichen Pfad, also den, in den als zuallererst hochgeladen wurde. Das erspart das Umkopieren, erschwert allerdings die Logik beim Löschen. Alternativ halt wie schon vorgeschlagen Umkopieren.

**Comment by webbird** [comment]
Noch besser wäre natürlich die Spalte aus _posts zu löschen und das Bild dann nur in _posts_img zu markieren.

**Comment by mrbaseman** [comment]
Ich nutze die Galerie nicht immer, manchmal nur das Beitragsbild oder noch nicht mal das. Da fände ich es ungeschickt wenn allein das Vorhandensein eines Beitragsbildes, was z.B. auch nur ein Logo sein kann, gleich eine Gallerie aufmachen würde.

Ich finde es auch sinnvoll dass die Bilder in den Beiträgen zugeordneten Unterverzeichnissen einsortiert sind.

Die Tabellen aufräumen,  damit Informationen nicht an verschiedenen Orten abgelegt sind, finde ich auch gut. Wenn man die Bilder irgendwie weiterverwenden will, macht es vielleicht schon Sinn, sie grundsätzlich über eine global fortlaufend durchnummerierte Id anzusprechen. 

Wenn man sie bei der Weiterverwendung umkopiert, kann man sich komplizierte Abfragen, ob sie noch anderswo in Verwendung sind, sparen.

**Comment by instantflorian** [comment]
Ich denke, es kann durchaus vorkommen, dass Beitrags- oder Gruppenbilder mehrfach verwendet werden, bei Galeriebildern ist das hingegen eher unwahrscheinlich. 
Hinzu kommt, dass, wenn alle Bilder im selben Verzeichnis lägen, ein unübersichtlicher Bilder-Blob mit hunderten Dateien entstünde, in dem nichts mehr wiederzufinden ist.
In sofern würde ich es sinnvoll finden, wenn es in der Tat für die Themen- und Beitragsbilder ein gemeinsames Verzeichnis gäbe, aus dem man dann ein Bilder herauspicken könnte, wenn man kein neues hochlädt, die Galeriebilder aber weiterhin jeweils in einem eigenen Verzeichnis landen.

Den CKFinder als Mediabrowser für NWI zu implementieren, halte ich für nicht so gut. Ich hoffe immer noch, dass irgendwann mal das Ding durch elFinder oder etwas ähnliches abgelöst wird bzw. es eine übergreifende Lösung für die Medienverwaltung gibt. 
Derzeit ist es übrigens so, dass das eigentlich geschützte/versteckte Verzeichnis .news_img im CKFinder angezeigt wird, nur wenn man darauf klickt, die Inhalte nicht angezeigt werden, sondern ein alert "Invalid folder name" erscheint - insofern würde es also wohl sowieso nicht funktionieren, CKFinder dafür zu verwenden.

**Comment by webbird** [comment]
Also ein Beitragsbild macht keine Galerie auf, das Problem entsteht eher, wenn man ein Galeriebild auch als Beitragsbild verwenden will. Da ist mir nämlich dann gestern aufgefallen, dass man damit ein Problem bekommt, wenn das Beitragsbild mit den Galeriebildern im gleichen Verzeichnis liegt. Derzeit ist es ja so, dass das Beitragsbild potentiell (viel) kleiner ist als die Galeriebilder. Man müßte also vom gewählten Galeriebild eine verkleinerte Version anlegen, die man dort aber nicht speichern kann, weil mit dem Namen ja schon das Galeriebild existiert.

Florians Ansatz halte ich daher für besser. Also alle Beitrags- und Gruppenbilder in .news_img und Galeriebilder in .news_img/PostID. Verwendet man dann ein Galeriebild auch als Beitragsbild, wird die verkleinerte Version im drüberliegenden Verzeichnis gespeichert und alles paßt wieder.

Übrigens finde ich es eine gute Idee, "Gruppen" in "Themen" umzubenennen. Das hat Florian zwar so nicht gesagt, aber ich glaube, er hat damit den Sinn von Gruppen präzisiert.

**Comment by webbird** [comment]
Ich habe im letzten Commit noch eine Debug-Ausgabe vergessen, ignoriert die einfach.

Ist noch kein Preview-Image vorhanden, kann man aus den anderen vorhandenen Bildern wählen.

![2019-07-18 19_13_48-WBCE»Verwaltung-Seiten](https://user-images.githubusercontent.com/147354/61477791-5cdec980-a990-11e9-929a-285eea3ce725.png)

Anmerkung: Da werden auch die Preview-Images von anderen Beiträgen angeboten, das ist aber noch nicht implementiert. Da muß ja eine Kopie erzeugt werden. Implementiert und getestet habe ich nur die Verwendung eines Galerie-Bilds, und da auch nur von den eigenen (=zum Posting gehörenden).

Ist ein Bild vorhanden, habe ich den Löschen-Link zum Button gemacht, samt roter Schriftfarbe beim :hover.

![2019-07-18 19_17_49-WBCE»Verwaltung-Seiten](https://user-images.githubusercontent.com/147354/61477943-c363e780-a990-11e9-9c04-c02bd0dc5d2c.png)

Unten ein kleiner (noch nicht ganz fertiger) Layout-Fix.

![2019-07-18 19_19_57-WBCE»Verwaltung-Seiten](https://user-images.githubusercontent.com/147354/61478079-189ff900-a991-11e9-8dab-d7793aef745b.png)

Da ich in der install/upgrade noch nicht alle Änderungen in den DB-Tabellen drin habe, hier ein SQL.

[nwi.zip](https://github.com/WBCE/News-with-Images/files/3407686/nwi.zip)

**Comment by webbird** [comment]
Ich habe die upgrade.php überarbeitet.
https://github.com/WBCE/News-with-Images/blob/master/upgrade.php

**Comment by webbird** [comment]
Wenn man viele Postings mit vielen Bildern hat, wird das Dropdown für die Auswahl eines Vorschaubildes aus den vorhandenen sehr lang. Irgendwie ist das alles Mist. Entweder wir schränken das ein - z.B. nur auf die Preview-Bilder von anderen Postings plus die Galerie-Bilder des aktuellen Postings - oder wir machen da einen vollständigen Media-Browser rein. Da das aber demnächst Coreseitig bearbeitet werden soll, würde ich das Faß jetzt ungern für ein Modul gesondert aufmachen wollen.

Vielleicht wäre es besser, das ganze Wiederverwenden von Bildern zurückzustellen. Was meint Ihr?

![2019-07-25 18_25_44-WBCE»Verwaltung-Seiten](https://user-images.githubusercontent.com/147354/61891578-3e397f00-af0a-11e9-9cbf-38c05f58fbd1.png)

**Comment by mrbaseman** [comment]
Kann man es auf einfache Weise ao wie in dem Screenshot machen, nur mit Scrollbar? Das wäre vielleicht ein Kompromiss so lange bis der Medienbrowser im Core aktualisiert ist

**Comment by webbird** [comment]
Ja, kann man schon, ich bin nur insgesamt irgendwie unzufrieden. Ich mach mal eine installierbare Version, dann könnt Ihr es ja mal testen.

**Comment by webbird** [comment]
https://github.com/WBCE/News-with-Images/issues/54#issuecomment-515474346
