### ISSUE TITLE
$wb->preprocess erzeugt Notices

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#56]
https://forum.wbce.org/viewtopic.php?pid=25196#p25196

**Comment by instantflorian** [comment]
[quote]
Hm.. ja, das kommt, weil die preprocess Methode bei WBCE "rausgeworfen" wurde und das ist wahrscheinlich nicht bei den Modulerstellern angekommen, die Notice nicht gesehen worden o.ä.
[/quote]
Hm... ich hab das jetzt mal geprüft, eine Notice sehe ich nicht obwohl ich bei Grundeinstellungen auf "Fehler und Warnungen anzeigen" geschaltet habe und bewusst produzierte Notices (Test mit Code2 > echo $foo; => Notice: Undefined variable) erscheinen.
Wo würde die NWI-spezifische Notice denn ausgegeben?

**Comment by webbird** [comment]
Spezifische Notices gibt es nicht, eine Notice ist eine Notice. Die Funktion ist zwar als obsolet markiert, existiert aber nach wie vor. (class.frontend.php ab Zeile 346.)

Edit: https://github.com/WBCE/WBCE_CMS/blob/641303f3955cd3e36d5ce4447c09f49f3beb0441/wbce/framework/class.frontend.php#L346

**Comment by mrbaseman** [comment]
da die Funktion in WB schon rausgeflogen ist und wblink auch in WBCE schon seit längerer Zeit per Outputfilter eingefügt werden, können wir auch auf preprocess verzichten: https://github.com/WBCE/News-with-Images/commit/5e0f055c8dd6855d7a6a076de2df7fa05e6d25d6

**Comment by webbird** [comment]
Spricht nichts gegen, aber es kann keine Notices geben, wenn die Funktion noch vorhanden ist.

**Comment by webbird** [comment]
Ist erledigt.
