### ISSUE TITLE
Add NWI support to SocialBaker

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#57]
Currently, the [SocialBaker Module](https://dev4me.com/modules-snippets/opensource/socialbaker/) can handle
- usual pages
- (Classic) news items
- Bakery items
- Topics items.

The support for NWI (page metadata / post image) should be added, once the way how images are stored is finalized.

**Comment by webbird** [comment]
Ist der Issue hier nicht falsch? Oder muss es dafür Änderungen im NWI geben?

**Comment by instantflorian** [comment]
Ist in erster Lnie als Gedächtnisstütze gedacht, wobei wie geschrieben 
die Anpassung von SocialBaker erst erfolgen kann, wenn feststeht, wie 
das Bilder-Handling erfolgt.
Allerdings könnte man sonst auch überlegen, evtl. den Social-Media-Kram 
direkt in NWI zu integrieren, also dass das Modul selbst die Metatags 
für Twitter und Facebook generiert.
