### ISSUE TITLE
NWI_USE_SECOND_BLOCK

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#58]
Derzeit wird bei der Installation des Moduls automatisch eine config.php erzeugt, die den 2. Block aktiviert. Das gilt dann aber für alle Instanzen des Moduls, also pauschal für alle Sektionen. Sollen wir das nicht lieber in die Einstellungen verschieben, so dass man es pro Sektion einstellen kann?

**Comment by instantflorian** [comment]
ja, abschnittsbezogene 2.-Block-Nutzung klingt sinnvoll.

**Comment by webbird** [comment]
Ist erledigt.
