### ISSUE TITLE
Falsche Uhrzeit im Kalender (?)

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#60]
Wählt man z.B. ein Startdatum aus, wird als Uhrzeit immer die aktuelle Zeit genommen. Ändere ich später das Datum, bleibt diese Uhrzeit erhalten, wenn ich sie nicht gezielt ändere. 

Beispiel: Startdatum xx, Uhrzeit 14:16 Uhr
Ich ändere das Datum auf YY, die Uhrzeit bleibt bei 14:16 Uhr

**Comment by instantflorian** [comment]
Ich glaube, das liegt am nicht ganz taufrischen Datepicker. 
Eigenartigerweise wird er mit der richtigen Uhrzeit initialisiert...

'
Calendar.setup(
		{
			inputField : "publishdate",
			ifFormat : "%d.%m.%Y %H:%M",
			button : "publishdate_trigger",
			firstDay : 1,
							showsTime : "true",
				timeFormat : "24",
						date : "2019/08/08 12:57",
			range : [1970, 2037],
			step : 1
		}
	);
	Calendar.setup(
		{
			inputField : "enddate",
			ifFormat : "%d.%m.%Y %H:%M",
			button : "enddate_trigger",
			firstDay : 1,
							showsTime : "true",
				timeFormat : "24",
						date : "2019/08/08 12:57",
			range : [1970, 2037],
			step : 1
		}
	);'

**Comment by webbird** [comment]
Hm, naja, die Uhrzeit zurückzusetzen ist ja vielleicht auch gar nicht gewollt. Vielleicht habe ich mich ja nur beim Datum vertan, wenn ich das nun ändere und die Uhrzeit wird automatisch auf 0 gesetzt, ist das ja vielleicht gar nicht das, was ich will. Vermutlich ist es am besten, das Verhalten unverändert zu lassen.
