### ISSUE TITLE
Anynews integrieren?

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#61]
Schon allein wegen der gemeinsamen Nutzung der Funktionen und der einheitlichen Darstellung wäre es doch eigentlich besser, Anynews direkt in NWI zu integrieren. Oder spricht was dagegen?

**Comment by instantflorian** [comment]
Nein, eigentlich spricht nichts dagegen. Der Aufruf auf Nicht-NWI-Seiten 
würde dann übers Droplet erfolgen? Und die Anpassbarkeit der Darstellung 
mittels der ja doch recht ambitionierten NIA-Templates bliebe bestehen?

**Comment by webbird** [comment]
Da es ja mittlerweile Hybrid-Module gibt, könnte der Aufruf via Function ja auch bleiben. Wobei ich da keinen Vorteil gegenüber dem Droplet sehe. Der einzige Haken wäre dass NIA bereits auf Twig aufsetzt, was ich bei NWI eigentlich nicht möchte, damit es kompatibel zu WB Classic bleibt.

Ansonsten müßte halt jemand ambitioniertes das NIA grundlegend anpassen. :)

**Comment by webbird** [comment]
So, ich habe das jetzt so weit intergriert, dass man das als einfachen Filter benutzen kann. Ausgabetemplates ("display_mode") gibt's erst mal keine, die Darstellung ist die "ganz normale" Liste, die man ja über das Backend anpassen kann. Sonst müßte man sich ja fragen, warum man die Beitragsschleife als solche im Backend konfigurieren kann, die anderen aber nicht.

Name der Funktion: mod_nwi_display_news_items
Name des Droplets: getNewsItems

Ich tendiere dazu, das Modul umzubenennen, z.B. in "Blog", weil des dem immer ähnlicher wird. Zudem ist "Blog" heutzutage ein geläufigerer Begriff als "News".
