### ISSUE TITLE
Verschieben von mehreren Beiträgen in Gruppe auf derselben Seite schlägt fehl

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#63]
Fehlermeldung:

Fatal error: Uncaught Error: Call to a member function get_post_escaped() on null in /.../modules/news_img/functions.inc.php:819 
Stack trace: 
#0 /.../modules/news_img/manage_posts.php(73): mod_nwi_post_move(1607, 484) 
#1 {main} thrown in /.../modules/news_img/functions.inc.php on line 819

**Comment by webbird** [comment]
Sollte behoben sein, Änderung ist aber nicht committet.

**Comment by instantflorian** [comment]
getestet, funktioniert
