### ISSUE TITLE
Filtern nach Tags / falsche Seitenzahlen

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#64]
Aus dem Forum:

Wenn man eine Tag-Übersichtsliste aufruft, also news.php?tag=xyz, erscheint trotzdem die Paginierung für alle Beiträge. D.h. wenn 5 Beiträge pro Seite angezeigt werden sollen, wird auch dann die vorherige Seite / Nächste Seite-Navigation angezeigt, wenn es nur 4 Beiträge mit dem Tag xyz gibt. Klickt man auf den Nächste-Seite-Link, wird die "komplette" News-Liste (nicht-tag-spezifisch) an der entsprechenden Paginierungs-Position angezeigt.

Erwartetes Verhalten:
- Bei weniger Beiträgen zum per Parameter übergebenen Tag als max. Beiträge pro Seite: keine Paginierung
- Bei mehr Beiträgen zum per Parameter übergebenen Tag als max. Beiträge pro Seite: Paginierung, wobei auch auf den Folgeseiten nur die Beiträge zum spezifizierten Tag aufgelistet werden; sollte dies nicht umsetzbar sein: keine Paginierung, d.h. es werden immer alle Beiträge zum spezifischen Tag auf einer Seite angezeigt.

**Comment by webbird** [comment]
Gefixt, aber noch nicht comittet

**Comment by instantflorian** [comment]
getestet, funktioniert teilweise. 
Ausgangssituation: Einstellung 5 Beiträge/Seite
Anzahl Beiträge mit Stichwort "wort": 6
Anzahl Beiträge ohne Stichwort: 6
=> Erwartetes Verhalten: Paginierung 1-5/6 funktioniert, aber auf der 2. Seite, auf der eigentlich nur der 6. Beitrag mit dem Stichwort "wort" erscheinen sollte, erscheinen dann auch alle Beiträge ohne Stichwort und die Paginierung zeigt nun "6-10 von 12"
