### ISSUE TITLE
Attribute vom Beitrags- und Gruppenbild in " statt '

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#65]
da sonst Probleme mit Ausdrücken, in denen Apostrophe vorkommen, auftreten.
Siehe https://forum.wbce.org/viewtopic.php?pid=27486#p27486

**Comment by webbird** [comment]
Das sehe ich nicht als Lösung, weil dann das Problem statt mit ' mit " auftreten würde. Korrekterweise sollte man alle Arten von Quotes umwandeln.

**Comment by mrbaseman** [comment]
stimmt. Einmal durch [htmlspecialchars](https://www.php.net/manual/de/function.htmlspecialchars.php)  schieben ist besser

**Comment by webbird** [comment]
Ist erledigt, aber nicht committet.

**Comment by instantflorian** [comment]
htmlentities reicht leider nicht:
![2019-10-11_121340](https://user-images.githubusercontent.com/1433754/66644506-625f4f00-ec21-11e9-923e-9910f63ca8b4.png)

**Comment by webbird** [comment]
Flag vergessen... Hab aber jetzt auch htmlspecialchars() genommen.
