### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#66]
- [x] Es wäre schön, wenn die Seiten im Menü angezeigt werden können -> erfordert vermutlich eine Änderung im SM2
- [x] Desgleichen gilt für den internen Link im CKE
- [x] Ein Droplet das nur die Beiträge auflistet (wie ein Menü) wäre praktisch -> die entsprechende Funktion könnte dann auch von SM2 verwendet werden
- [x] Es wäre schön, eine Möglichkeit zu haben, entweder das Beitragsbild oder - wenn das fehlt - als Fallback das Gruppenbild anzuzeigen
- [x] "Massenaktion": Zuweisen / Ändern der Gruppe für mehrere Beiträge gleichzeitig (analog Kopieren, Stichworte zuordnen)

**Comment by mrbaseman** [comment]
CKE ist mit [6ff9fcf](https://github.com/WBCE/WBCE_CMS/commit/6ff9fcfd8717324fb4e5dcaa48e71836d54ccfd2) schon erledigt. Das war eigentlich schon in WBCE 1.4.0 drin, hat aber nicht wie vorgesehen funktioniert, denn inzwischen muss man beim SQL Quoting ein bisschen mehr Sorgfalt walten lassen ;)

**Comment by webbird** [comment]
Cool!

**Comment by webbird** [comment]
Für den Fall "Beitrags- oder Gruppenbild" hab ich mir überlegt, einfach ein neues Markup dafür zu erstellen. Also [GROUP_IMAGE] - [POST_IMAGE] - neu [POST_OR_GROUP_IMAGE]. Dann kann die Logik dafür in der Funktion erfolgen und wir brauchen keine Option dafür.

**Comment by webbird** [comment]
Ich hätte da einen Hack für SM2, der auch für andere Module nutzbar wäre.

Neues Flag: `SM2_INCLUDE_MODS`
Wenn das Flag gesetzt ist, wird in allen Modulen vom Typ "page" und "snippet" (könnt Ihr ja bei Bedarf noch ändern/erweitern) nach einer Datei `sm2_include.php` gesucht.
Diese definiert eine Funktion `sm2_<MODULNAME>_get_pages` (wobei MODULNAME der aus der Spalte directory ist).

Die Funktion liefert dann eine Liste von Unterseiten.

![2019-10-10 18_15_31-WBCE - Sec 56 mit Tag global](https://user-images.githubusercontent.com/147354/66587325-799f2d80-eb8a-11e9-88a5-c2cd314206d1.png)

[include.zip](https://github.com/WBCE/News-with-Images/files/3713576/include.zip)

Ich habe erst mal nur geschaut dass es funktioniert, nicht nach der Performance. Auch Seiteneffekte auf andere Flags habe ich erst mal außen vor gelassen, also insbesondere sowas wie den max. Level, "nur Siblings" etc. Das sollte nach Möglichkeit jemand in die Hand nehmen, der das SM2 besser kennt.

Beispiel aus der index.php im WBCEZon:
$aOptions       = SM2_ALL|SM2_PRETTY|SM2_BUFFER|SM2_INCLUDE_MODS,

**Comment by instantflorian** [comment]
Her damit (aber nur, wenn das veganes Soja-Hack ist !11!eins)

**Comment by webbird** [comment]
include.php für SM2 im Beitrag, Update für news_img im Forum.

**Comment by webbird** [comment]
Zum Droplet: Es gibt jetzt einen Parameter aslist, der auf 1 zu setzen ist, dann bekommt man eine ul ohne Gruppen und ohne SHORT, also nur die Titel.
