### ISSUE TITLE
NWI erscheint nach Installation nicht in der Liste der installierten Module

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#67]
Zudem wird bei einem Update die Versionsnummer nicht aktualisiert.

Kann das bitte jemand übernehmen, der mehr Kenntnisse zum WBCE-Modul-Installations-Mechanismus hat? In BC funktioniert das.

**Comment by mrbaseman** [comment]
im info.php ist die "neue" Versionsnummer eingetragen? Wenn ja, dann kann ich mir höchstens vorstellen, dass das `  $admin->print_footer();` am Ende dafür sorgt, dass der upgrade-Mechanismus aussteigt, bevor die Versionsnummer aktualisiert ist. In meinen Modulen habe ich den Aufruf nämlich im upgrade.php nicht drin.

**Comment by instantflorian** [comment]
das liegt an dem aufgerufenen Core-Dropletinstaller. Ich hatte im 
Forenthread irgendwo eine Alternativmöglichkeit gepostet, mit der die 
Probleme nicht auftreten.

**Comment by webbird** [comment]
Ah, okay, aber da hatte ich ja gemeint, dass man besser das Droplets-Modul repariert. Soll ich das trotzdem erst mal ins NWI einbauen?

**Comment by instantflorian** [comment]
ja bitte.

**Comment by webbird** [comment]
Erledigt, aber noch nicht committet.

**Comment by instantflorian** [comment]
getestet, Fehler tritt nicht mehr auf
