### ISSUE TITLE
Probleme mit 2. Block 

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#74]
1.  Checkbox "2. Block verwenden" nach Update von NWI 4.0.1 deaktiviert - evtl. müsste beim Update geprüft werden, ob bisher der 2. Block verwendet wurde (also ob bei einem oder mehreren existierenden Beiträgen das DB-Feld content_block2 nicht leer ist) und in diesem Falle die Nutzung des zweiten Blocks aktiviert werden/bleiben

2. Aktivieren von "2. Block verwenden" zeigt im Frontend keine Auswirkungen, d.h. weder bei den News-Einstellungen noch einzelnen News-Beiträgen hinterlegte Inhalte erscheinen im FE

3. Nach Aktivierung der Checkbox wird im BE zwar ein zusätzliches Eingabefeld angezeigt, die dort vorgenommenen Eingaben werden jedoch nicht gespeichert; erst beim erneuten Aufruf werden die Eingaben gespeichert (aber, wie erwähnt, nicht m FE angezeigt)

**Comment by webbird** [comment]
Für FE gefixt

**Comment by webbird** [comment]
Für BE gefixt

Bleibt noch Punkt 1.

**Comment by webbird** [comment]
Punkt 1 sollte dann jetzt auch gefixt ein. Die upgrade.php bindet die config.php ein, wenn sie existiert, und prüft den Wert der Konstanten NWI_USE_SECOND_BLOCK. Wenn der true ist, wird der zweite Block für alle Sektionen aktiviert.
