### ISSUE TITLE
Vorheriger Beitrag / Nächster Beitrag falsch belegt

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#75]
Folgende News gibt es:
![nwi1](https://user-images.githubusercontent.com/1433754/70929534-9b59dc80-2033-11ea-8d5a-0411fe5553f2.jpg)
Einstellung für News-Footer:
![nwi4](https://user-images.githubusercontent.com/1433754/70929596-b88eab00-2033-11ea-9cb7-622226f0610e.jpg)
Darstellung Übersicht im Frontend:
![nwi2](https://user-images.githubusercontent.com/1433754/70929554-a3b21780-2033-11ea-9873-03e3e3663d5d.jpg)
Darstellung News-Detailansicht im Frontend:
![nwi3](https://user-images.githubusercontent.com/1433754/70929613-c2b0a980-2033-11ea-948f-abf63dcb89d2.jpg)
Der Link "Vorheriger Beitrag" ist hier mit Beitrag 2 verlinkt, der sowohl in der benutzerdefinierten Beitragssortierung als auch bei zeitgesteuerter Veröffentlichung nach meinem Dafürhalten der _nächste_ Beitrag wäre.

**Comment by webbird** [comment]
Ändert nichts an der möglicherweise falschen Sortierung, aber auf der Detailseite ist der Default für das Markup jetzt:

```
<div class="mod_nwi_spacer"></div>
<table class="mod_nwi_table" style="visibility: [DISPLAY_PREVIOUS_NEXT_LINKS]">
<tr>
    <td class="mod_nwi_table_left">[PREVIOUS_PAGE_LINK]</td>
    <td class="mod_nwi_table_right">[NEXT_PAGE_LINK]</td>
</tr>
</table>
<div class="mod_nwi_tags">[TAGS]</div>
```

**Comment by webbird** [comment]
Hmmmm.... also der letzte Beitrag in der Liste ist Beitrag 1, der davor/darüber Beitrag 2, also ist die Verlinkung aus meiner Sicht richtig. Man liest ja auch von oben nach unten. Bei Beitrag 2 wäre der vorige Beitrag 3 und der nächste Beitrag 1.
