### ISSUE TITLE
Droplet getimagenewsitems: CKE zu schlau

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#78]
Der CKE wandelt
```[[getImageNewsItems?group_id=display_mode=5&max_news_items=6&not_older_than=50]]```
um in
```[[getImageNewsItems?group_id=1&display_mode=5&max_news_items=6¬_older_than=50]]``` 
weil er die Kombination ampersand-not für die HTML-Enität des Not-Symbols hält. Und wer braucht schon Semikolons. Der CKE jedenfalls nicht.
Um dieses Problem zu umgehen, müsste/könnte das Droplet dahingehend geändert werden, dass ausschließlich im Droplet-Aufruf (auch) als  _is_not_older_than_ an Stelle von not_older_than verwendet werden kann.

**Comment by webbird** [comment]
Beide Parameter werden jetzt unterstützt, wobei is_not_older_than not_older_than überschreibt, falls beide gesetzt sind.
