### ISSUE TITLE
Update-Probleme, wenn kein Verzeichnis posts vorhanden

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#79]
Siehe
https://forum.wbce.org/viewtopic.php?pid=30308#p30308

**Comment by webbird** [comment]
Was ist das erwartete Verhalten? Dass kein Fehler protokolliert wird, oder dass das Verzeichnis beim Upgrade angelegt wird?

**Comment by webbird** [comment]
Die upgrade.php ignoriert die Nicht-Existenz des Verzeichnisses. Sie legt das Verzeichnis aber nicht an.
