### ISSUE TITLE
(Perma?)link (name of access file)

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#8]
* Auto-generate from title on add
* Do not change when title changes later (?)

**Comment by mrbaseman** [comment]
auto-generation from title, but perhaps try to shorten it if needed?

**Comment by webbird** [comment]
Yeah, but shorten to... what?

**Comment by mrbaseman** [comment]
sowas wie maximal 50 Zeichen oder 3 Wörter:
`$kurztitel= preg_replace('/(\w+\s?\w*\s?\w*).*/', '$1', substr($titel,0,50))`

**Comment by webbird** [comment]
Bis auf weiteres implementiert:

* Sichtbares Eingabefeld für den Link
* Beim Tippen in das Titel-Feld wird der Link automatisch generiert (jQuery Plugin)
* Link ist änderbar, ABER wenn der Titel geändert wird, wird durch das JavaScript auch wieder der Link geändert

**Comment by mrbaseman** [comment]
ich habe gerade gemerkt, dass nach dem Kopieren eines Beitrags der Link erstmal leer ist. Sobald man ein Zeichen im Titel ändert, wird der Link aktualisiert. Mal schauen, wie das dann mit der Implementierung von #11 wird. Ich sehe daher im Moment keinen Handlungsbedarf, ich wollte meine Beobachtung nur dokumentieren, damit es nicht in Vergessenheit gerät.

**Comment by instantflorian** [comment]
Ihc hab das mal als Bug gekennzeichnet, weil ich da durchaus Handlungsbedarf sehe... es entspricht mMn einem erwartbaren Verhalten. Da die Posts ja zwangsweise mit der eindeutigen Post-ID versehen werden, spricht mMn nichts dagegen, den Beitragslink mit zu kopieren.

**Comment by mrbaseman** [comment]
ja, hast recht. Ich meinte eher dass das vielleicht unter die Kategorie "Schönheitsfehler" fällt, da man den kopierten Beitrag ja - zumindest in der alten Mehtode direkt zum Editieren angeboten bekommen hat und i.d.R. dann auch was am Titel macht. Sollte aber jetzt behoben sein (siehe #11)
