### ISSUE TITLE
Version 5.0 offenbar nicht kompatibel mit PHP 5.6 / 7.0

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#80]
functions.inc.php verwendet Nullable Types, siehe
https://forum.wbce.org/viewtopic.php?pid=30502#p30502
=> There was an unknown exception: syntax error, unexpected '?', expecting variable (T_VARIABLE) in line (1693) of /modules/news_img/functions.inc.php

**Comment by webbird** [comment]
Ich entwickle ausschließlich für > 7.1, also nur für aktuell supportete Versionen. Davon würde ich auch nicht abweichen wollen. 

https://www.php.net/supported-versions.php

**Comment by ghost** [comment]
Aus aktueller Sicht würde ich sagen dass das ein wontfix bleiben wird.

**Comment by webbird** [comment]
Jepp. Bin momentan sowieso krank.
