### ISSUE TITLE
Doppelter Output, wenn NWI mehrfach auf einer Seite

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#85]
Wenn mehr als ein NWI-Abschnitt auf einer Seite ist, wird in der Beitragsansicht der jeweilige Beitrag in *allen* auf der Seite vorhandenen NWI-Abschnitten ausgegeben. 
Beispiel:
Auf der Seite x gibt es die NWI-Abschnitte mit der Section-ID 12, 13 und 14
Nur (!) Im Abschnitt 12 ist ein Beitrag hinterlegt
Klickt man nun bei dem betr. Abschnitt auf "Weiterlesen", so erscheint dieser 3x komplett mit Überschrift, Kurz- und Langtext.

**Comment by ghost** [comment]
Dieses Verhalten kann man als Issue by Design ansehen
