### ISSUE TITLE
PHP 8.1 errors

### ISSUE THREAD

**Issue by webbird** [WBCE/News-with-Images#94]
[Deprecated] \framework\class.database.php:[383] from \modules\news_img\functions.inc.php:[1728] database->escapeString "mysqli_real_escape_string(): Passing null to parameter #2 ($string) of type string is deprecated"
[Deprecated] /modules/news_img/functions.inc.php:[1475] from /modules/news_img/functions.inc.php:[1206] mod_nwi_img_get_by_post "explode(): Passing null to parameter #2 ($string) of type string is deprecated"
[Deprecated] /modules/news_img/view.php:[121] from /framework/frontend.functions.php:[485] block_contents "strlen(): Passing null to parameter #1 ($string) of type string is deprecated"

**Comment by ghost** [comment]
a few more errors:

[Deprecated] \modules\news_img\functions.inc.php:[1475]  from \modules\news_img\functions.inc.php:[1206] mod_nwi_img_get_by_post "explode(): Passing null to parameter #2 ($string) of type string is deprecated"

[Deprecated] \modules\news_img\view.php:[119]  from \framework\frontend.functions.php:[485] block_contents "strlen(): Passing null to parameter #1 ($string) of type string is deprecated"
[Deprecated] \modules\news_img\view.php:[123]  from \framework\frontend.functions.php:[485] block_contents "strlen(): Passing null to parameter #1 ($string) of type string is deprecated"
[Deprecated] \modules\news_img\view.php:[121]  from \framework\frontend.functions.php:[485] block_contents "strlen(): Passing null to parameter #1 ($string) of type string is deprecated"

one more:
[Warning] /modules/news_img/upgrade.php:[283]  from /install/update.php:[515]  "Undefined variable $module_directory"

**Comment by ghost** [comment]
should be fixed with 927bccc997798c8ac67b43c7928120eac1dfdf64
