### ISSUE TITLE
Beitragssortierung bei Gruppenzuordnung

### ISSUE THREAD

**Issue by instantflorian** [WBCE/News-with-Images#96]
Sind Beiträge Gruppen zugeordnet, ist es nicht mehr möglich, diese nach Datum oder ID automatisch sortiert im Frontend auszugeben, nicht einmal innerhalb der Gruppe. Ich klassifiziere das mal als Bug, weil das aktuelle Verhalten es in der Tat wenig sinnvoll erscheint.
Es sollte die Möglichkeit bestehen, Beiträge auch dann - wahlweise innerhalb einer Gruppe oder übergreifend - nach den angebotenen Kriterien zu sortieren, wenn sie Gruppen zugeordnet sind.

**Comment by mrbaseman** [comment]
Ist halt die Frage, wozu die Gruppen gedacht sind. Mir hat sich das bisher nicht so wirklich erschlossen. Wenn ich mich nicht irre, ist im Frontend die Auswirkung, dass die Beiträge aus einer Gruppe immer zusammen dargestellt werden. 
Die Sortierung sollte aber innerhalb der Gruppe dann greifen.
